// frontend-vue/src/components/form/Button.vue
<template>
    <component
        :is="tagConfig.tag"
        v-bind="tagConfig.props"
        :class="['btn', colorClass, inverseClass, customClasses]"
        @click="clickHandler"
    >
        <slot />
    </component>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";

import type { ButtonType, CssClass } from "@/types";

// Props
const props = defineProps<{
    disabled?: boolean;
    inverse?: boolean;
    color?: "primary" | "secondary" | "success" | "warning" | "danger";
    class?: CssClass;
    to?: string;
    href?: string;
    type?: ButtonType;
}>();

// Events
const emit = defineEmits<{
    (e: "click"): void;
}>();

// Computed
const disabled = computed(() => props.disabled ?? false);

const customClasses = computed(() => props.class || "");

const inverseClass = computed(() =>
    props.inverse && !disabled.value ? "inverse" : ""
);

const colorClass = computed(() =>
    disabled.value ? "disabled" : props.color || "primary"
);

const tagConfig = computed(() => {
    if (props.href) {
        return {
            tag: "a",
            props: { href: props.href },
        };
    }
    if (props.to) {
        return {
            tag: RouterLink,
            props: { to: props.to },
        };
    }
    return {
        tag: "button",
        props: {
            type: props.type || "button",
            disabled: props.disabled ?? false,
        },
    };
});

// Handlers
const clickHandler = () => {
    if (!props.disabled) emit("click");
};
</script>

<style lang="css">
@reference "@/main.css";

.btn {
    @apply inline-block px-6 py-2 rounded-md text-base font-medium;
    @apply transition-colors duration-200 focus:outline-none;
}
</style>

// frontend-angular/src/components/form/button/button.ts
import { Component, computed, input, output } from '@angular/core';
import { RouterLink } from '@angular/router';

import type { ButtonType, CssClass } from '@/types';

@Component({
    selector: 'app-button',
    templateUrl: './button.html',
    styleUrl: './button.css',
    imports: [RouterLink],
})
export class Button {
    // Inputs
    disabled = input<boolean>(false);
    inverse = input<boolean>(false);
    color = input<'primary' | 'secondary' | 'success' | 'warning' | 'danger'>('primary');
    customClass = input<CssClass>('');
    to = input<string>();
    href = input<string>();
    type = input<ButtonType>('button');

    // Outputs
    clicked = output<void>();

    // Computed
    inverseClass = computed(() => (this.inverse() && !this.disabled() ? 'inverse' : ''));
    colorClass = computed(() => (this.disabled() ? 'disabled' : this.color()));
    isAnchor = computed(() => !!this.href() && !this.to());
    isRouterLink = computed(() => !!this.to() && !this.href());

    // Handlers
    clickHandler() {
        if (!this.disabled()) {
            this.clicked.emit();
        }
    }
}
