// frontend-angular/src/components/user/user-item/user-item.ts
import { Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import { Avatar } from '@/components/ui';
import { userPlacesRoute } from '@/router';
import type { User } from '@/types';

const placeholder = '/avatar_placeholder.jpg';

@Component({
    selector: 'app-user-item',
    templateUrl: './user-item.html',
    styleUrl: './user-item.css',
    imports: [RouterLink, Avatar],
})
export class UserItem {
    // Init
    protected readonly userPlacesRoute = userPlacesRoute;

    // Inputs
    user = input.required<User>();

    // Computed
    imageUrl = computed(() => this.user().image_url || placeholder);

    placeNumber = computed(() => {
        const number = this.user().places.length;
        if (number > 1) {
            return `${number} Places`;
        }
        return `${number} Place`;
    });
}

// frontend-react/src/components/user/UserItem.tsx
import "./UserItem.css";

import { Link } from "react-router-dom";

import { Avatar } from "@/components/ui";
import { userPlacesRoute } from "@/router";
import type { User } from "@/types";

const placeholder = "/public/avatar_placeholder.jpg";

interface UserItemProps {
    user: User;
}

const UserItem: React.FC<UserItemProps> = ({ user }) => {
    const number = user.places.length;
    let placeNumber = `${number} Place`;
    if (number > 1) {
        placeNumber = `${number} Places`;
    }

    return (
        <li className="user-item">
            <div className="card">
                <Link to={userPlacesRoute(user.id)} className="user-item-link">
                    <div className="user-avatar">
                        <Avatar
                            imageUrl={user.image_url || placeholder}
                            alt={user.name}
                        />
                    </div>
                    <div className="user-info">
                        <h2>{user.name}</h2>
                        <h3>{placeNumber}</h3>
                    </div>
                </Link>
            </div>
        </li>
    );
};

export default UserItem;
