// frontend-react/src/components/form/Input.tsx
import { ChangeEvent, ElementType, useState } from "react";

interface InputProps {
    onInput: (value: string) => void;
    value?: string;
    isValid?: boolean;
    id: string;
    label: string;
    className?: string;
    element?: "input" | "textarea";
    type?: HTMLInputElement["type"];
    disabled?: boolean;
    rows?: number;
    placeholder?: string;
    errorText?: string;
}

const Input: React.FC<InputProps> = ({
    onInput,
    value,
    isValid,
    id,
    label,
    className,
    element,
    type,
    disabled,
    rows,
    placeholder,
    errorText,
}) => {
    const [isTouched, setIsTouched] = useState<boolean>(false);

    const changeHandler = (
        event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
    ) => {
        onInput(event.target.value);
    };

    const touchHandler = () => {
        if (!disabled) setIsTouched(true);
    };

    const isError = !isValid && isTouched;

    let Tag: ElementType = "input";
    const tagProps: Record<string, any> = {
        value: value || "",
        id,
        onChange: changeHandler,
        onBlur: touchHandler,
        className: disabled ? "disabled" : "active",
        disabled: disabled ?? false,
    };

    switch (element) {
        case "textarea":
            Tag = "textarea";
            tagProps.rows = rows || 3;
            break;
        case "input":
        default:
            tagProps.type = type;
            tagProps.placeholder = placeholder;
            break;
    }

    return (
        <div
            className={`input-container ${className || "basis-full"} ${isError ? "error" : ""}`}
        >
            <label htmlFor={id}>{label}</label>
            <Tag {...tagProps} />
            <p className={`error-text ${isError ? "" : "invisible"}`}>
                {errorText || "The input is not valid"}
            </p>
        </div>
    );
};

export default Input;

// frontend-vue/src/components/form/Input.vue
<template>
    <div class="input-container" :class="[widthClass, { error: isError }]">
        <label :for="props.id">{{ props.label }}</label>
        <component
            :is="tagConfig.tag"
            :id="props.id"
            v-bind="tagConfig.tagProps"
            @blur="inputTouched"
            @input="valueChanged"
        />
        <p class="error-text" :class="{ invisible: !isError }">
            {{ props.errorText || "The input is not valid" }}
        </p>
    </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import { validate, ValidatorType } from "@/lib";

const props = defineProps<{
    element?: "input" | "textarea";
    type?: HTMLInputElement["type"];
    id: string;
    label: string;
    onInput: (value: string, isValid: boolean) => void;
    width?: string;
    padding?: string;
    rows?: number;
    placeholder?: string;
    validators?: ValidatorType[];
    errorText?: string;
    value?: string;
    isValid?: boolean;
}>();

const widthClass = computed(() => {
    if (props.width) {
        return `basis-${props.width} ${props.padding ?? ""}`;
    } else {
        return "basis-full";
    }
});

const data = ref<string>(props.value || "");
const isValid = ref<boolean>(props.isValid || false);
const isTouched = ref<boolean>(false);

const inputTouched = () => {
    isTouched.value = true;
};

const valueChanged = (event: Event) => {
    const target = event.target as HTMLInputElement | HTMLTextAreaElement;
    data.value = target.value;
    const valid = props.validators
        ? validate(data.value, props.validators)
        : true;
    isValid.value = valid;
    props.onInput(data.value, valid);
};

const isError = computed(() => !isValid.value && isTouched.value);

const tagConfig = computed(() => {
    let tag = "input";
    const tagProps: Record<string, any> = {};
    switch (props.element) {
        case "textarea":
            tag = "textarea";
            tagProps.rows = props.rows || 3;
            break;
        case "input":
        default:
            tagProps.type = props.type;
            tagProps.placeholder = props.placeholder;
            break;
    }
    return { tag, tagProps };
});
</script>

<style lang="css">
@reference "../../main.css";

@layer components {
    .input-container {
        @apply mb-4;
    }

    .input-container label {
        @apply block mb-2 font-semibold text-pen error:text-danger;
    }

    .input-container textarea,
    .input-container input {
        @apply w-full rounded-md border px-3 py-2;
        @apply text-pen border-pen-ruler bg-surface-alt;
        @apply focus:border-secondary focus:outline-none;
        @apply error:bg-danger-surface error:border-danger;
    }

    .input-container .error-text {
        @apply mt-1 text-sm text-danger;
    }
}
</style>
