// frontend-angular/src/components/form/input/input.ts
import { Component, computed, input, model, signal } from '@angular/core';

import type { CssClass } from '@/types';

@Component({
    selector: 'app-input',
    templateUrl: './input.html',
    styleUrl: './input.css',
})
export class Input {
    // Model
    value = model.required<string>();

    // Inputs
    id = input.required<string>();
    label = input.required<string>();
    isValid = input<boolean>();
    customClass = input<CssClass>('basis-full');
    element = input<'input' | 'textarea'>('input');
    type = input<HTMLInputElement['type']>();
    step = input<string>();
    disabled = input<boolean>(false);
    rows = input<number>(3);
    placeholder = input<string>();
    errorText = input<string>('The input is not valid');

    // Signals
    isTouched = signal<boolean>(false);

    // Computed
    showError = computed(() => !this.isValid() && this.isTouched());

    inputClass = computed(() => ({
        disabled: this.disabled(),
        active: !this.disabled(),
    }));

    containerClass = computed(() => [this.customClass(), { error: this.showError() }]);

    isTextarea = computed(() => this.element() === 'textarea');

    // Handlers
    onInput(event: InputEvent): void {
        this.value.set((event.target as HTMLInputElement).value);
    }

    onBlur(): void {
        if (!this.disabled()) this.isTouched.set(true);
    }
}

// frontend-vue/src/components/form/Input.vue
<template>
    <div class="input-container" :class="[customClass, { error: showError }]">
        <label :for="props.id">{{ props.label }}</label>
        <component
            v-model="value"
            @input="$emit('update:modelValue', $event.target.value)"
            @blur="inputTouched"
            :value="value"
            :is="tagConfig.tag"
            :id="props.id"
            :class="inputClass"
            v-bind="tagConfig.tagProps"
        />
        <p class="error-text" :class="{ invisible: !showError }">
            {{ props.errorText || "The input is not valid" }}
        </p>
    </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import type { CssClass } from "@/types";

// Models
const value = defineModel<string>({ required: true });

// Props
const props = defineProps<{
    id: string;
    label: string;
    isValid?: boolean;
    class?: CssClass;
    element?: "input" | "textarea";
    type?: HTMLInputElement["type"];
    step?: string;
    disabled?: boolean;
    rows?: number;
    placeholder?: string;
    errorText?: string;
}>();

// State
const isTouched = ref<boolean>(false);

// Computed
const customClass = computed(() => {
    if (!props.class) {
        return "basis-full";
    }
    return props.class;
});

const inputClass = computed(() => ({
    disabled: props.disabled,
    active: !props.disabled,
}));

const showError = computed(() => !props.isValid && isTouched.value);

const tagConfig = computed(() => {
    let tag = "input";
    const tagProps: Record<string, any> = { disabled: props.disabled ?? false };
    switch (props.element) {
        case "textarea":
            tag = "textarea";
            tagProps.rows = props.rows || 3;
            break;
        case "input":
        default:
            tagProps.type = props.type;
            tagProps.step = props.step;
            tagProps.placeholder = props.placeholder;
            break;
    }
    return { tag, tagProps };
});

// Handlers
const inputTouched = () => {
    if (!props.disabled) isTouched.value = true;
};
</script>

<style scoped lang="css">
@reference "@/main.css";

.input-container {
    @apply mb-4;
}

.input-container label {
    @apply block mb-2 font-semibold text-pen error:text-danger;
}

.input-container textarea,
.input-container input {
    @apply w-full rounded-md border px-3 py-2;
}

.input-container textarea.active,
.input-container input.active {
    @apply text-pen border-pen-ruler bg-surface-alt;
    @apply focus:border-secondary focus:outline-none;
    @apply error:bg-danger-surface error:border-danger;
}

.input-container .error-text {
    @apply mt-1 text-sm text-danger;
}
</style>
