// frontend-react/src/components/ui/Backdrop.tsx
import { createPortal } from "react-dom";

interface BackdropProps {
    onClick: () => void;
}

const Backdrop: React.FC<BackdropProps> = ({ onClick }) => {
    return createPortal(
        <div
            className="fixed top-0 left-0 w-full h-screen bg-stone-300 opacity-70 z-10"
            onClick={onClick}
        ></div>,
        document.getElementById("backdrop-hook")!
    );
};

export default Backdrop;

// frontend-vue/src/components/ui/Backdrop.vue
<template>
    <teleport to="#backdrop-hook">
        <div class="modal-backdrop" @click="emit('click')"></div>
    </teleport>
</template>

<script setup lang="ts">
// Events
const emit = defineEmits<{
    (e: "click"): void;
}>();
</script>

<style lang="css">
@reference "@/main.css";

.modal-backdrop {
    @apply fixed top-0 left-0 w-full h-screen bg-backdrop opacity-70 z-10;
}
</style>
