// frontend-svelte/src/components/ui/Backdrop.svelte
<script lang="ts">
import { onMount, onDestroy } from "svelte";

// Setup
let backdropElement: HTMLElement | undefined;
const targetElement = document.getElementById("backdrop-hook"); 

// Props
const {onClick} = $props<{
    onClick: () => void
}>()

// Events
onMount(() => {
    if (targetElement && backdropElement) {
        targetElement.appendChild(backdropElement);
    }
});

onDestroy(() => {
    targetElement?.removeChild(backdropElement!)
});
</script>

<div
    role="button"
    tabindex="0"
    class="modal-backdrop"
    onkeydown={onClick}
    onclick={onClick}
    bind:this={backdropElement}
></div>

<style lang="css">
@reference "@/main.css";

.modal-backdrop {
    @apply fixed top-0 left-0 w-full h-screen bg-backdrop opacity-70 z-10;
}
</style>

// frontend-vue/src/components/ui/Backdrop.vue
<template>
    <teleport to="#backdrop-hook">
        <div class="modal-backdrop" @click="emit('click')"></div>
    </teleport>
</template>

<script setup lang="ts">
// Events
const emit = defineEmits<{
    (e: "click"): void;
}>();
</script>

<style lang="css">
@reference "@/main.css";

.modal-backdrop {
    @apply fixed top-0 left-0 w-full h-screen bg-backdrop opacity-70 z-10;
}
</style>
