// frontend-angular/src/services/backend.ts
import { HttpStatusCode } from '@angular/common/http';
import { Injectable, signal } from '@angular/core';
import type { AxiosInstance, AxiosResponse } from 'axios';
import axios from 'axios';
import { AxiosError } from 'axios';

import { getToken } from '@/storage';
import type { HeaderContent, HttpMethods } from '@/types';

const TOKEN_EXPIRED = 'Token expired';

interface State {
    loading: boolean;
    statusCode?: number;
    json?: any;
    error?: {
        tokenExpired?: boolean;
        message: string;
        response?: any;
    };
}

interface BackendOptions {
    ignoreNotFound?: boolean;
    tokenRequired?: boolean;
}

const getClient = (contentType: HeaderContent, token: string): AxiosInstance => {
    const headers = {
        'Content-Type': contentType,
        ...(token && { Authorization: token }),
    };

    return axios.create({
        baseURL: `${import.meta.env.VITE_BACKEND_URL}`,
        headers,
    });
};

@Injectable({ providedIn: 'root' })
export class BackendService {
    private abortController: AbortController | null = null;

    httpData = signal<State>({ loading: false });

    clear() {
        this.httpData.set({ loading: false });
    }

    private handleSuccess(resp: AxiosResponse) {
        this.httpData.set({
            loading: false,
            statusCode: resp.status,
            json: resp.data,
        });
    }

    private handleError(err: AxiosError) {
        const statusCode = err.status || 500;
        const response = err.response;
        const data = response?.data as { message?: string } | undefined;
        const message = data?.message || 'Something went wrong!';
        const tokenExpired = message === TOKEN_EXPIRED;

        this.httpData.set({
            loading: false,
            statusCode,
            error: {
                tokenExpired,
                message,
                response,
            },
        });
    }

    async sendRequest(url: string, method: HttpMethods, data?: any, options: BackendOptions = {}) {
        // Create abort controller
        this.abortController?.abort();
        this.abortController = new AbortController();

        // Check the Token
        const token = getToken();
        const tokenRequired = options.tokenRequired ?? true;
        if (!token && tokenRequired) {
            this.abortController = null;
            this.httpData.set({
                loading: false,
                error: {
                    tokenExpired: true,
                    message: TOKEN_EXPIRED,
                },
            });
            // We raise the same error as if we actually send
            // a request and got a token expired response
            throw new Error(TOKEN_EXPIRED);
        }

        // Get the http client
        let contentType: HeaderContent = 'application/json';
        if (data instanceof FormData) {
            contentType = 'multipart/form-data';
        } else if (data instanceof URLSearchParams) {
            contentType = 'application/x-www-form-urlencoded';
        }
        const webClient = getClient(contentType, token);

        try {
            // Send the request
            this.httpData.set({ loading: true });
            const resp = await webClient[method](url, data, {
                signal: this.abortController.signal,
            });
            this.handleSuccess(resp);
            return resp;
        } catch (err) {
            // Handle error
            if (err instanceof AxiosError) {
                if (err.response?.status === HttpStatusCode.NotFound && options.ignoreNotFound) {
                    this.handleSuccess(err.response);
                    return err.response;
                } else {
                    this.handleError(err);
                }
            }

            throw err;
        } finally {
            this.abortController = null;
        }
    }
}

// frontend-react/src/hooks/backend.ts
import type { AxiosInstance, AxiosResponse } from "axios";
import axios, { AxiosError, HttpStatusCode } from "axios";
import { useCallback, useEffect, useReducer, useRef } from "react";

import { getToken } from "@/storage";
import type { HeaderContent, HttpMethods } from "@/types";

const TOKEN_EXPIRED = "Token expired";

// STATE

interface State {
    loading: boolean;
    statusCode?: number;
    json?: Record<string, any>;
    error?: {
        tokenExpired?: boolean;
        message: string;
        response?: AxiosResponse;
    };
}

const emptyState: State = { loading: false };

// ACTIONS

enum ActionType {
    STORED_TOKEN_EXPIRED,
    SEND_REQUEST,
    PARSE_RESPONSE,
    PARSE_ERROR,
    CLEAR_ERROR,
}

interface StoredTokenExpiredAction {
    type: ActionType.STORED_TOKEN_EXPIRED;
}

interface SendRequestAction {
    type: ActionType.SEND_REQUEST;
}

interface ParseResponseAction {
    type: ActionType.PARSE_RESPONSE;
    payload: AxiosResponse;
}

interface ParseErrorAction {
    type: ActionType.PARSE_ERROR;
    payload: AxiosError;
}

interface ClearErrorAction {
    type: ActionType.CLEAR_ERROR;
}

type Action =
    | StoredTokenExpiredAction
    | SendRequestAction
    | ParseResponseAction
    | ParseErrorAction
    | ClearErrorAction;

// REDUCER

const reducer = (state: State, action: Action): State => {
    switch (action.type) {
        case ActionType.STORED_TOKEN_EXPIRED:
            return {
                loading: false,
                error: {
                    tokenExpired: true,
                    message: TOKEN_EXPIRED,
                },
            };
        case ActionType.SEND_REQUEST:
            return { loading: true };
        case ActionType.PARSE_RESPONSE:
            return {
                loading: false,
                statusCode: action.payload.status,
                json: action.payload.data,
            };
        case ActionType.PARSE_ERROR: {
            const statusCode = action.payload.status || 500;
            const response = action.payload.response;
            const data = response?.data as { message?: string } | undefined;
            const message = data?.message || "Something went wrong!";
            const tokenExpired = message === TOKEN_EXPIRED;
            return {
                loading: false,
                statusCode,
                error: { tokenExpired, message, response },
            };
        }
        case ActionType.CLEAR_ERROR:
            return { loading: false };
        default:
            return state;
    }
};

// HELPERS

const getBackend = (
    contentType: HeaderContent,
    token: string
): AxiosInstance => {
    const headers = {
        "Content-Type": contentType,
        ...(token && { Authorization: token }),
    };

    return axios.create({
        baseURL: `${import.meta.env.VITE_BACKEND_URL}`,
        headers,
    });
};

// HOOK

interface useBackendOptions {
    ignoreNotFound?: boolean;
}

type SendRequestType = <T>(
    url: string,
    method: HttpMethods,
    data?: Record<string, any>,
    tokenRequired?: boolean
) => Promise<AxiosResponse<T>>;

type ClearErrorType = () => void;

export const useBackend = (
    options: useBackendOptions = {}
): [State, SendRequestType, ClearErrorType] => {
    const abortControllerRef = useRef<AbortController>(null);
    const [state, dispatch] = useReducer(reducer, emptyState);

    const sendRequest = useCallback(
        async <T>(
            url: string,
            method: HttpMethods,
            data?: object,
            tokenRequired: boolean = true
        ): Promise<AxiosResponse<T>> => {
            // Create abort controller
            abortControllerRef.current?.abort();
            abortControllerRef.current = new AbortController();

            // Check the Token
            const token = getToken();
            if (!token && tokenRequired) {
                dispatch({ type: ActionType.STORED_TOKEN_EXPIRED });
                abortControllerRef.current = null;
                // We raise the same error as if we actually send
                // a request and got a token expired response
                throw new AxiosError(TOKEN_EXPIRED);
            }

            // Prepare the web client
            let contentType: HeaderContent = "application/json";
            if (data instanceof FormData) {
                contentType = "multipart/form-data";
            } else if (data instanceof URLSearchParams) {
                contentType = "application/x-www-form-urlencoded";
            }
            const webClient = getBackend(contentType, token);

            try {
                // Send Request
                dispatch({ type: ActionType.SEND_REQUEST });
                const resp = await webClient[method](url, data, {
                    signal: abortControllerRef.current.signal,
                });

                // Handle good response
                dispatch({
                    type: ActionType.PARSE_RESPONSE,
                    payload: resp,
                });
                return resp;
            } catch (err) {
                // Handle error
                if (err instanceof AxiosError) {
                    if (
                        err.response?.status === HttpStatusCode.NotFound &&
                        options.ignoreNotFound
                    ) {
                        dispatch({
                            type: ActionType.PARSE_RESPONSE,
                            payload: err.response,
                        });
                        return err.response;
                    } else {
                        dispatch({
                            type: ActionType.PARSE_ERROR,
                            payload: err,
                        });
                        throw err;
                    }
                }
                throw err;
            } finally {
                abortControllerRef.current = null;
            }
        },
        [options.ignoreNotFound]
    );

    const clear = useCallback(() => {
        dispatch({ type: ActionType.CLEAR_ERROR });
    }, []);

    useEffect(() => {
        return () => {
            abortControllerRef.current?.abort();
        };
    }, []);

    return [state, sendRequest, clear];
};
