// frontend-react/src/components/places/PlaceItem.tsx
import { useState } from "react";

import placeholder from "../../assets/place_placeholder.jpg";
import { Button } from "../../components/form";
import { HttpError, LoadingSpinner, Map, Modal } from "../../components/ui";
import { useHttp } from "../../lib";
import { useAppSelector } from "../../store";
import { Place } from "../../types";

interface PlaceItemProps {
    place: Place;
    onDelete: () => void;
}

const PlaceItem: React.FC<PlaceItemProps> = ({ place, onDelete }) => {
    const authData = useAppSelector((state) => state.auth.data);
    const [data, sendRequest, clearError] = useHttp();
    const [showMap, setShowMap] = useState(false);
    const [showDeleteModal, setShowDeleteModal] = useState(false);

    const openMapHanlder = (): void => {
        setShowMap(true);
    };

    const closeMapHanlder = (): void => {
        setShowMap(false);
    };

    const openDeleteModal = (): void => {
        setShowDeleteModal(true);
    };

    const closeDeleteModal = (): void => {
        setShowDeleteModal(false);
    };

    const onDelteHandler = (): void => {
        setShowDeleteModal(false);
        sendRequest(`/places/${place.id}`, "delete").then(() => {
            onDelete();
        });
    };

    const deleteModalFooter = (
        <>
            <Button color="danger" onClick={onDelteHandler}>
                DELETE
            </Button>
            <Button onClick={closeDeleteModal}>CANCEL</Button>
        </>
    );
    return (
        <>
            {data.error && (
                <HttpError error={data.error} onClear={clearError} />
            )}
            {data.loading && (
                <div className="center">
                    <LoadingSpinner asOverlay />
                </div>
            )}
            <Modal
                show={showMap}
                onCancel={closeMapHanlder}
                header={place.address}
                footer={
                    <Button inverse onClick={closeMapHanlder}>
                        CLOSE
                    </Button>
                }
            >
                <Map
                    position={place.location}
                    zoom={13}
                    markerText={place.title}
                />
            </Modal>
            <Modal
                show={showDeleteModal}
                onCancel={closeDeleteModal}
                header="Are you sure?"
                footer={deleteModalFooter}
            >
                <p>Do you want to proceed and delete this place?</p>
            </Modal>

            <li className="place-item">
                <div className="card place-item-card">
                    <div className="image-container">
                        <img
                            src={place.imageUrl || placeholder}
                            alt={place.title}
                        />
                    </div>
                    <div className="place-info">
                        <h2>{place.title}</h2>
                        <h2>{place.address}</h2>
                        <p>{place.description}</p>
                    </div>
                    <div className="place-actions">
                        <Button
                            color="secondary"
                            inverse
                            onClick={openMapHanlder}
                        >
                            VIEW ON MAP
                        </Button>
                        {authData?.userId === place.creatorId && (
                            <Button to={`/places/${place.id}`}>EDIT</Button>
                        )}
                        {authData?.userId === place.creatorId && (
                            <Button color="danger" onClick={openDeleteModal}>
                                DELETE
                            </Button>
                        )}
                    </div>
                </div>
            </li>
        </>
    );
};

export default PlaceItem;

// frontend-svelte/src/components/places/PlaceItem.svelte
<script lang="ts">
import placeholder from "@/assets/place_placeholder.jpg";
import { Button } from "@/components/form";
import { HttpError, LoadingSpinner, Map, Modal } from "@/components/ui";
import { useHttp } from "@/lib";
import { authStore } from "@/store";
import type { Place } from "@/types";

// Init
const loggedUserId = authStore.userId;
const { httpData, sendRequest, clear } = useHttp();

// Props
const props = $props<{
    place: Place;
    onDelete: () => void;
}>();

// States
let showMap = $state<boolean>(false);
let showDeleteModal = $state<boolean>(false);

// Computed
const isUserOwned = $derived<boolean>($loggedUserId === props.place.creatorId);
const imageUrl = $derived(props.place.imageUrl || placeholder);

// Handlers
const openMapHandler = () => {
    showMap = true;
};

const closeMapHandler = () => {
    showMap = false;
};

const openDeleteModalHandler = () => {
    showDeleteModal = true;
};

const closeDeleteModalHandler = () => {
    showDeleteModal = false;
};

const deleteHandler = () => {
    closeDeleteModalHandler();
    sendRequest(`/places/${props.place.id}`, "delete").then(() => {
        props.onDelete();
    });
};
</script>

{#if $httpData.error?.message}
    <HttpError onClose={clear} error={$httpData.error} />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
<Modal onClose={closeMapHandler} show={showMap} header={props.place.address}>
    <Map
        position={props.place.location}
        zoom={13}
        markerText={props.place.title}
    />
    {#snippet footer()}
        <Button inverse onClick={closeMapHandler}>CLOSE</Button>
    {/snippet}
</Modal>
<Modal
    onClose={closeDeleteModalHandler}
    show={showDeleteModal}
    header="Are you sure?"
>
    <p class="delete-text-messaage">
        Do you want to proceed and delete this place?
    </p>
    {#snippet footer()}
        <Button color="danger" onClick={deleteHandler}>DELETE</Button>
        <Button onClick={closeDeleteModalHandler}>CANCEL</Button>
    {/snippet}
</Modal>
<li class="place-item">
    <div class="card place-item-card">
        <div class="image-container">
            <img src={imageUrl} alt={props.place.title} />
        </div>
        <div class="place-info">
            <h2>{props.place.title}</h2>
            <h2>{props.place.address}</h2>
            <p>{props.place.description}</p>
        </div>
        <div class="place-actions">
            <Button onClick={openMapHandler} color="secondary" inverse>
                VIEW ON MAP
            </Button>
            <Button to={`/places/${props.place.id}`}>EDIT</Button>
            {#if isUserOwned}
                <Button color="danger" onClick={openDeleteModalHandler}>
                    DELETE
                </Button>
            {/if}
        </div>
    </div>
</li>

<style lang="css">
@reference "@/main.css";

.delete-text-messaage {
    @apply p-5;
}

li.place-item {
    @apply my-4;
}

.place-item-card {
    @apply p-0;
}

.place-item .image-container {
    @apply w-full h-52 md:h-80 mr-6;
}

.place-item-card img {
    @apply w-full h-full object-cover;
}

.place-item .place-info {
    @apply p-4 text-center;
}

.place-item .place-info h2,
.place-item .place-info p {
    @apply mb-2;
}

.place-item .place-actions {
    @apply p-4 text-center border-t border-pen-ruler;
}

.place-item .place-actions :global(.btn) {
    @apply mx-1;
}
</style>
