// frontend-react/src/components/places/PlaceCreateForm.tsx
import { useNavigate } from "react-router-dom";

import type { FormConfig } from "@/lib";
import { minLengthValidator, numericValidator, useForm, useHttp } from "@/lib";
import { useAppSelector } from "@/store";

import { Button, ImageUpload, Input } from "../form";
import { HttpError, LoadingSpinner } from "../ui";

const CreatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
    image: { initial: { file: null, url: "" } },
};

type FieldsType = keyof typeof CreatePlaceFormConfig;

const NewPlace: React.FC = () => {
    const navigate = useNavigate();
    const authData = useAppSelector((state) => state.auth.data);
    const [data, sendRequest, clearError] = useHttp();
    const [state, inputHandlers] = useForm<FieldsType>(CreatePlaceFormConfig);

    const onSubmit = async (e: React.FormEvent): Promise<void> => {
        e.preventDefault();
        const formData = new FormData();
        formData.append("title", state.fields.title.value);
        formData.append("description", state.fields.description.value);
        formData.append("address", state.fields.address.value);
        formData.append("lat", state.fields.lat.value);
        formData.append("lng", state.fields.lng.value);
        formData.append("creator_id", authData?.user_id as any);
        if (state.fields.image.value.file) {
            formData.append("image", state.fields.image.value.file);
        }
        try {
            await sendRequest("/places/", "post", formData);
            navigate("/");
        } catch (err) {
            console.log(err);
        }
    };

    return (
        <>
            {data.error?.message && (
                <HttpError error={data.error} onClear={clearError} />
            )}
            <form className="place-create" onSubmit={onSubmit}>
                {data.loading && <LoadingSpinner asOverlay />}
                <Input
                    onInput={inputHandlers.title}
                    value={state.fields.title.value}
                    isValid={state.fields.title.valid}
                    id="title"
                    element="input"
                    type="text"
                    label="Title"
                    errorText="Please enter a valid Title"
                />
                <Input
                    onInput={inputHandlers.address}
                    value={state.fields.address.value}
                    isValid={state.fields.address.valid}
                    id="address"
                    element="input"
                    type="text"
                    label="Address"
                    errorText="Please enter a valid address"
                />
                <Input
                    onInput={inputHandlers.description}
                    value={state.fields.description.value}
                    isValid={state.fields.description.valid}
                    id="description"
                    element="textarea"
                    label="Description"
                    errorText="Please enter a valid Description"
                />
                <Input
                    onInput={inputHandlers.lat}
                    value={state.fields.lat.value}
                    isValid={state.fields.lat.valid}
                    id="latitude"
                    className="basis-full sm:basis-1/2 sm:pr-2"
                    element="input"
                    type="number"
                    step="any"
                    label="Latitude"
                    errorText="Please enter a valid Latitude"
                />
                <Input
                    onInput={inputHandlers.lng}
                    value={state.fields.lng.value}
                    isValid={state.fields.lng.valid}
                    id="longitude"
                    className="basis-full sm:basis-1/2 sm:pl-2"
                    element="input"
                    type="number"
                    step="any"
                    label="Longitude"
                    errorText="Please enter a valid Longitude"
                />
                <ImageUpload
                    onInput={inputHandlers.image}
                    value={state.fields.image.value}
                    isValid={state.fields.image.valid}
                    id="image"
                    color="secondary"
                />
                <div className="buttons">
                    <Button
                        type="submit"
                        color="secondary"
                        disabled={!state.valid}
                    >
                        Add Place
                    </Button>
                </div>
            </form>
        </>
    );
};

export default NewPlace;

// frontend-svelte/src/components/places/PlaceCreateForm.svelte
<script lang="ts">
import { goto } from "@mateothegreat/svelte5-router";

import { Button, ImageUpload, Input } from "@/components/form";
import { HttpError, LoadingSpinner } from "@/components/ui";
import type { FormConfig } from "@/lib";
import { minLengthValidator, numericValidator, useForm, useHttp } from "@/lib";
import { authStore } from "@/store";

// Init
const loggedUserId = authStore.userId;
const { httpData, sendRequest, clear } = useHttp();

// Form
const CreatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
    image: { initial: { file: null, url: "" } },
};

type FieldsType = keyof typeof CreatePlaceFormConfig;

const { fields, formValid } = useForm<FieldsType>(CreatePlaceFormConfig);
const { title, address, description, lat, lng, image } = fields;

// Handlers
const submitHandler = async (e: Event) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append("title", $title.value);
    formData.append("image", $image.value.file);
    formData.append("description", $description.value);
    formData.append("address", $address.value);
    formData.append("lat", $lat.value);
    formData.append("lng", $lng.value);
    formData.append("creator_id", $loggedUserId as any);
    try {
        await sendRequest("/places/", "post", formData);
        goto("/");
    } catch (err) {
        console.log(err);
    }
};
</script>

{#if $httpData.error?.message}
    <HttpError onClose={clear} error={$httpData.error} />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
<form onsubmit={submitHandler} class="place-create">
    <Input
        bind:value={$title.value}
        bind:valid={$title.valid}
        id="title"
        element="input"
        type="text"
        label="Title"
        errorText="Please enter a valid Title"
    />
    <Input
        bind:value={$address.value}
        bind:valid={$address.valid}
        id="address"
        element="input"
        type="text"
        label="Address"
        errorText="Please enter a valid address"
    />
    <Input
        bind:value={$description.value}
        bind:valid={$description.valid}
        id="description"
        element="textarea"
        label="Description"
        errorText="Please enter a valid Description"
    />
    <Input
        bind:value={$lat.value}
        bind:valid={$lat.valid}
        class="basis-full sm:basis-1/2 sm:pr-2"
        id="latitude"
        element="input"
        type="number"
        step="any"
        label="Latitude"
        errorText="Please enter a valid Latitude"
    />
    <Input
        bind:value={$lng.value}
        bind:valid={$lng.valid}
        class="basis-full sm:basis-1/2 sm:pl-2"
        id="longitude"
        element="input"
        type="number"
        step="any"
        label="Longitude"
        errorText="Please enter a valid Longitude"
    />
    <ImageUpload
        bind:value={$image.value}
        bind:valid={$image.valid}
        id="image"
        color="secondary"
    />
    <div class="buttons">
        <Button disabled={!$formValid} type="submit" color="secondary">
            Add Place
        </Button>
    </div>
</form>

<style lang="css">
@reference "@/main.css";

.place-create {
    @apply flex flex-wrap;
    @apply relative w-[90%] max-w-160 my-0 mx-auto p-4;
    @apply list-none shadow-md rounded-md bg-surface;
}

.place-create .buttons {
    @apply w-full mt-10 text-right;
}
</style>
