// frontend-svelte/src/components/navigation/SideDrawer.svelte
<script lang="ts">
import { onDestroy, onMount } from "svelte";
import { fly } from "svelte/transition";

// Init
const targetElement = document.getElementById("drawer-hook");

// Props
const { show, onClick, children } = $props<{
    show: boolean;
    onClick: () => void;
    children?: () => unknown;
}>();

// States
let drawerElement = $state<HTMLElement | undefined>(undefined);
let drawerWidth = $state<number>(0);

// Events
onMount(() => {
    if (targetElement && drawerElement) {
        updateWidth();
        window.addEventListener("resize", updateWidth);
        targetElement.appendChild(drawerElement);
    }
});

onDestroy(() => {
    if (targetElement && drawerElement) {
        targetElement.removeChild(drawerElement!);
        window.removeEventListener("resize", updateWidth);
    }
});

// Handlers
const updateWidth = () => {
    if (drawerElement) drawerWidth = drawerElement.offsetWidth;
};
</script>

{#if show}
    <div
        role="button"
        tabindex="0"
        onkeydown={onClick}
        onclick={onClick}
        class="sidedrawer"
        bind:this={drawerElement}
        transition:fly={{ x: -drawerWidth, duration: 200, opacity: 0 }}
    >
        {@render children?.()}
    </div>
{/if}

<style lang="css">
@reference "@/main.css";

.sidedrawer {
    @apply fixed z-40 top-0 left-0 h-screen w-[70%];
    @apply bg-surface shadow-md;
}
</style>

// frontend-vue/src/components/navigation/SideDrawer.vue
<template>
    <Teleport to="#drawer-hook">
        <Transition name="sidedrawer-transition" appear>
            <aside v-if="show" class="sidedrawer" @click="emit('click')">
                <slot />
            </aside>
        </Transition>
    </Teleport>
</template>

<script setup lang="ts">
// Props
defineProps<{
    show: boolean;
}>();

// Events
const emit = defineEmits<{
    (e: "click"): void;
}>();
</script>

<style scoped lang="css">
@reference "@/main.css";

aside.sidedrawer {
    @apply fixed z-40 top-0 left-0 h-screen w-[70%];
    @apply bg-surface shadow-md;
}

.sidedrawer-transition-enter-active,
.sidedrawer-transition-leave-active {
    @apply transform transition duration-200;
}

.sidedrawer-transition-enter-from,
.sidedrawer-transition-leave-to {
    @apply -translate-x-full opacity-0;
}

.sidedrawer-transition-enter-to,
.sidedrawer-transition-leave-from {
    @apply translate-x-0 opacity-100;
}
</style>
