// frontend-react/src/components/user/UsersList.tsx
import "./UsersList.css";

import type { User } from "@/types";

import UserItem from "./UserItem";

interface UserListProps {
    items: User[];
}

const UsersList: React.FC<UserListProps> = ({ items }) => {
    if (items.length === 0) {
        return (
            <div className="no-users">
                <div className="card">
                    <h2>No Users found!</h2>
                </div>
            </div>
        );
    }
    return (
        <ul className="users-list">
            {items.map((item: User) => {
                return <UserItem key={item.id} user={item} />;
            })}
        </ul>
    );
};

export default UsersList;

// frontend-angular/src/components/user/users-list/users-list.ts
import { Component, computed, input } from '@angular/core';

import type { User } from '@/types';

import { UserItem } from '../user-item/user-item';

@Component({
    selector: 'app-users-list',
    templateUrl: './users-list.html',
    styleUrl: './users-list.css',
    imports: [UserItem],
})
export class UsersList {
    // Inputs
    items = input.required<User[]>();

    // Computed
    noUsers = computed(() => this.items().length === 0);
}
