// frontend-vue/src/components/ui/ErrorModal.vue
<template>
    <Modal
        :onCancel="props.onClear"
        :show="!!props.error"
        :header="props.header || `An Error Occured!`"
    >
        <p>{{ props.error }}</p>
        <template #footer>
            <Button :onClick="props.onClear">Okay</Button>
        </template>
    </Modal>
</template>

<script setup lang="ts">
import { Button } from "@/components/form";

import Modal from "./Modal.vue";

// Props
const props = defineProps<{
    error?: string;
    header?: string;
    onClear: () => void;
}>();
</script>

// frontend/src/shared/components/ui/ErrorModal.tsx
import React from "react";

import Modal from "./Modal";
import { Button } from "../form";

interface ErrorModelProps {
    error: string;
    header?: string;
    onClear: () => void;
}

const ErrorModal: React.FC<ErrorModelProps> = ({ error, header, onClear }) => {
    return (
        <Modal
            onCancel={onClear}
            header={header || "An Error Occurred!"}
            show={!!error}
            footer={<Button onClick={onClear}>Okay</Button>}
        >
            <p>{error}</p>
        </Modal>
    );
};

export default ErrorModal;
