// frontend-angular/src/components/place/place-update-form/place-update-form.ts
import type { OnInit } from '@angular/core';
import { Component, inject, input, signal } from '@angular/core';
import { form, FormRoot, minLength, validate } from '@angular/forms/signals';
import { Router } from '@angular/router';

import { Button, Input } from '@/components/form';
import { HttpError, LoadingSpinner } from '@/components/ui';
import { AppRoute } from '@/router';
import { BackendService } from '@/services';
import type { Place } from '@/types';

interface PlaceUpdateFormModel {
    title: string;
    address: string;
    description: string;
    lat: number;
    lng: number;
}

@Component({
    selector: 'app-place-update-form',
    templateUrl: './place-update-form.html',
    styleUrl: './place-update-form.css',
    imports: [Button, Input, LoadingSpinner, HttpError, FormRoot],
    providers: [BackendService],
})
export class PlaceUpdateForm implements OnInit {
    // Init
    private router = inject(Router);
    backend = inject(BackendService);

    // Inputs
    placeId = input.required<string>();

    // State
    model = signal<PlaceUpdateFormModel>({
        title: '',
        address: '',
        description: '',
        lat: 0,
        lng: 0,
    });

    // Form
    placeForm = form(this.model, (path) => {
        minLength(path.title, 10, { message: 'Please enter a valid Title' });
        minLength(path.address, 1, { message: 'Please enter a valid address' });
        minLength(path.description, 10, { message: 'Please enter a valid Description' });

        validate(path.lat, (ctx) =>
            Number.isFinite(ctx.value())
                ? null
                : { kind: 'numeric', message: 'Please enter a valid Latitude' }
        );
        validate(path.lng, (ctx) =>
            Number.isFinite(ctx.value())
                ? null
                : { kind: 'numeric', message: 'Please enter a valid Longitude' }
        );
    });

    // Events
    ngOnInit() {
        this.backend.sendRequest<Place>(`/places/${this.placeId()}`, 'get').then((resp) => {
            const { data } = resp;
            this.model.set({
                title: data.title,
                address: data.address,
                description: data.description,
                lat: data.location.lat,
                lng: data.location.lng,
            });
        });
    }

    // Handlers
    private async submit() {
        const value = this.model();

        try {
            await this.backend.sendRequest(`/places/${this.placeId()}`, 'put', {
                title: value.title,
                address: value.address,
                description: value.description,
                location: {
                    lat: value.lat,
                    lng: value.lng,
                },
            });
            this.router.navigateByUrl(AppRoute.HOME);
        } catch (err) {
            console.log(err);
        }
    }

    onSubmit(e: Event) {
        e.preventDefault();
        this.submit();
    }
}

// frontend-react/src/components/places/PlaceUpdateForm.tsx
import "./PlaceUpdateForm.css";

import { useEffect } from "react";
import { useNavigate } from "react-router-dom";

import type { FormConfig } from "@/hooks";
import { useBackend, useForm } from "@/hooks";
import { AppRoute } from "@/router";
import type { Place } from "@/types";
import { minLengthValidator, numericValidator } from "@/utils";

import { Button, Input } from "../form";
import { HttpError, LoadingSpinner } from "../ui";

const UpdatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
};

type FieldsType = keyof typeof UpdatePlaceFormConfig;

interface PlaceUpdateFormProps {
    placeId: string;
}

const PlaceUpdateForm: React.FC<PlaceUpdateFormProps> = ({ placeId }) => {
    const navigate = useNavigate();
    const [state, inputHandlers, prefillData] = useForm<FieldsType>(
        UpdatePlaceFormConfig
    );
    const [data, sendRequest, clearError] = useBackend();

    useEffect(() => {
        sendRequest<Place>(`/places/${placeId}`, "get").then((resp) => {
            const { data } = resp;
            prefillData({
                title: data.title,
                address: data.address,
                description: data.description,
                lat: String(data.location.lat),
                lng: String(data.location.lng),
            });
        });
    }, [sendRequest, prefillData, placeId]);

    const submitHandler = async (e: React.FormEvent): Promise<void> => {
        e.preventDefault();
        try {
            await sendRequest(`/places/${placeId}`, "put", {
                title: state.fields.title.value,
                address: state.fields.address.value,
                description: state.fields.description.value,
                location: {
                    lat: state.fields.lat.value,
                    lng: state.fields.lng.value,
                },
            });
            navigate(AppRoute.HOME);
        } catch (err) {
            console.log(err);
        }
    };

    if (data.error?.message) {
        return <HttpError error={data.error} onClear={clearError} />;
    }

    if (data.loading) {
        return <LoadingSpinner asOverlay />;
    }

    return (
        <form className="place-update" onSubmit={submitHandler}>
            <Input
                onInput={inputHandlers.title}
                value={state.fields.title.value}
                isValid={state.fields.title.valid}
                id="title"
                element="input"
                type="text"
                label="Title"
                errorText="Please enter a valid Title"
            />
            <Input
                onInput={inputHandlers.address}
                value={state.fields.address.value}
                isValid={state.fields.address.valid}
                id="address"
                element="input"
                type="text"
                label="Address"
                errorText="Please enter a valid Address"
            />
            <Input
                onInput={inputHandlers.description}
                value={state.fields.description.value}
                isValid={state.fields.description.valid}
                id="description"
                element="textarea"
                label="Description"
                errorText="Please enter a valid Description"
            />
            <Input
                onInput={inputHandlers.lat}
                value={state.fields.lat.value}
                isValid={state.fields.lat.valid}
                id="latitude"
                className="basis-full sm:basis-1/2 sm:pr-2"
                element="input"
                type="number"
                step="any"
                label="Latitude"
                errorText="Please enter a valid Latitude"
            />
            <Input
                onInput={inputHandlers.lng}
                value={state.fields.lng.value}
                isValid={state.fields.lng.valid}
                id="longitude"
                className="basis-full sm:basis-1/2 sm:pl-2"
                element="input"
                type="number"
                step="any"
                label="Longitude"
                errorText="Please enter a valid Longitude"
            />
            <div className="buttons">
                <Button type="submit" color="secondary" disabled={!state.valid}>
                    Edit Place
                </Button>
            </div>
        </form>
    );
};

export default PlaceUpdateForm;
