// frontend-svelte/src/components/places/PlacesList.svelte
<script lang="ts">
import { Button } from "@/components/form";
import { AppRoute } from "@/router";
import type { Place } from "@/types";

import PlaceItem from "./PlaceItem.svelte";

// Props
const props = $props<{
    sameAuthenticatedUser?: boolean;
    items: Place[];
    onDelete: () => void;
}>();
</script>

<ul class="places-list">
    {#if props.items.length > 0}
        {#each props.items as place (place.id)}
            <PlaceItem {place} onDelete={props.onDelete} />
        {/each}
    {:else if props.sameAuthenticatedUser}
        <div class="no-places">
            <div class="card">
                <h2>No places found. Maybe create one?</h2>
                <Button color="secondary" to={AppRoute.NEW_PLACE}>Share</Button>
            </div>
        </div>
    {:else}
        <div class="no-places">
            <div class="card">
                <h2>This user has not created places yet</h2>
            </div>
        </div>
    {/if}
</ul>

<style lang="css">
@reference "@/main.css";

.places-list {
    @apply w-[90%] max-w-160 my-4 mx-auto p-0 list-none;
}

.no-places {
    @apply mx-auto w-100 max-w-[90%];
}

.no-places .card {
    @apply p-5 text-center;
}

.no-places .card h2 {
    @apply my-5;
}
</style>

// frontend-react/src/components/places/PlacesList.tsx
import "./PlacesList.css";

import { AppRoute } from "@/router";
import type { Place } from "@/types";

import { Button } from "../form";
import PlaceItem from "./PlaceItem";

interface PlaceListProps {
    sameAuthenticatedUser: boolean;
    items: Place[];
    onDelete: () => void;
}

const PlaceList: React.FC<PlaceListProps> = ({
    items,
    onDelete,
    sameAuthenticatedUser,
}) => {
    if (items.length > 0) {
        return (
            <ul className="places-list">
                {items.map((p: Place) => {
                    return (
                        <PlaceItem key={p.id} place={p} onDelete={onDelete} />
                    );
                })}
            </ul>
        );
    }

    if (sameAuthenticatedUser) {
        return (
            <div className="no-places">
                <div className="card">
                    <h2>No places found. Maybe create one?</h2>
                    <Button color="secondary" to={AppRoute.NEW_PLACE}>
                        Share
                    </Button>
                </div>
            </div>
        );
    }

    return (
        <div className="no-places">
            <div className="card">
                <h2>This user has not created places yet</h2>
            </div>
        </div>
    );
};

export default PlaceList;
