// frontend-vue/src/components/ui/ErrorModal.vue
<template>
    <Modal
        @close="emit('close')"
        :show="!!props.error"
        :header="props.header || `An Error Occured!`"
    >
        <p class="text-error">{{ props.error }}</p>
        <template #footer>
            <Button @click="emit('close')">Okay</Button>
        </template>
    </Modal>
</template>

<script setup lang="ts">
import { Button } from "@/components/form";

import Modal from "./Modal.vue";

// Props
const props = defineProps<{
    error?: string;
    header?: string;
}>();

// Events
const emit = defineEmits<{
    (e: "close"): void;
}>();
</script>

<style lang="css">
@reference "@/main.css";

.text-error {
    @apply p-5;
}
</style>

// frontend-svelte/src/components/ui/ErrorModal.svelte
<script lang="ts">
import { Button } from "@/components/form";

import Modal from "./Modal.svelte";

// Props
const {
    error,
    header = "An Error Occured!",
    onClose,
} = $props<{
    error?: string;
    header?: string;
    onClose: () => void;
}>();
</script>

<Modal {onClose} show={!!error} {header}>
    <p class="text-error">{error}</p>
    {#snippet footer()}
        <Button onClick={onClose}>Okay</Button>
    {/snippet}
</Modal>


<style lang="css">
@reference "@/main.css";

.text-error {
    @apply p-5;
}
</style>
