// frontend-angular/src/components/ui/map/map.ts
import type { ElementRef, OnDestroy } from '@angular/core';
import { afterNextRender, Component, effect, input, viewChild } from '@angular/core';
import type { Map as LeafletMap, Marker } from 'leaflet';
import * as L from 'leaflet';

import type { Location } from '@/types';

@Component({
    selector: 'app-map',
    templateUrl: './map.html',
    styleUrl: './map.css',
})
export class Map implements OnDestroy {
    // Init
    private map: LeafletMap | null = null;
    private marker: Marker | null = null;

    // ViewChild
    private mapDiv = viewChild.required<ElementRef<HTMLDivElement>>('mapDiv');

    // Inputs
    position = input.required<Location>();
    zoom = input.required<number>();
    markerText = input.required<string>();

    // Handlers
    private readonly _onMount = afterNextRender(() => {
        const pos = this.position();
        this.map = L.map(this.mapDiv().nativeElement).setView([pos.lat, pos.lng], this.zoom());

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution:
                '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(this.map);

        this.marker = L.marker([pos.lat, pos.lng]).addTo(this.map).bindPopup(this.markerText());

        this.map.invalidateSize();
    });

    private readonly _onUpdate = effect(() => {
        const pos = this.position();
        if (this.map && this.marker) {
            this.marker.setLatLng([pos.lat, pos.lng]);
            this.map.setView([pos.lat, pos.lng], this.zoom());
        }
    });

    ngOnDestroy() {
        this.map?.remove();
    }
}

// frontend-svelte/src/components/ui/Map.svelte
<script lang="ts">
import type { Map as LeafletMap, Marker } from "leaflet";
import * as L from "leaflet";
import { onMount } from "svelte";

import type { Location } from "@/types";

// Init
let mapDiv: HTMLDivElement;
let map: LeafletMap;
let marker: Marker;

// Props
const { position, zoom, markerText } = $props<{
    position: Location;
    zoom: number;
    markerText: string;
}>();

// Events
onMount(() => {
    map = L.map(mapDiv).setView([position.lat, position.lng], zoom);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
            '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);
    marker = L.marker([position.lat, position.lng])
        .addTo(map)
        .bindPopup(markerText);

    map.invalidateSize();
    return () => map.remove();
});

// Effects
$effect(() => {
    if (map && marker) {
        marker.setLatLng([position.lat, position.lng]);
        map.setView([position.lat, position.lng], zoom);
    }
});
</script>

<div bind:this={mapDiv} class="map-container"></div>

<style lang="css">
@reference "@/main.css";

.map-container {
    @apply w-full h-50;
}
</style>
