// frontend-svelte/src/components/places/PlaceItem.svelte
<script lang="ts">
import { Button } from "@/components/form";
import { HttpError, LoadingSpinner, Map, Modal } from "@/components/ui";
import { useBackend } from "@/composables";
import { updatePlaceRoute } from "@/router";
import { authStore } from "@/store";
import type { Place } from "@/types";

// Init
const placeholder = "/place_placeholder.jpg";
const loggedUserId = authStore.userId;
const { httpData, sendRequest, clear } = useBackend();

// Props
const props = $props<{
    place: Place;
    onDelete: () => void;
}>();

// States
let showMap = $state<boolean>(false);
let showDeleteModal = $state<boolean>(false);

// Computed
const isUserOwned = $derived<boolean>($loggedUserId === props.place.creator_id);
const imageUrl = $derived(props.place.image_url || placeholder);

// Handlers
const openMapHandler = () => {
    showMap = true;
};

const closeMapHandler = () => {
    showMap = false;
};

const openDeleteModalHandler = () => {
    showDeleteModal = true;
};

const closeDeleteModalHandler = () => {
    showDeleteModal = false;
};

const deleteHandler = () => {
    closeDeleteModalHandler();
    sendRequest(`/places/${props.place.id}`, "delete").then(() => {
        props.onDelete();
    });
};
</script>

{#if $httpData.error?.message}
    <HttpError onClose={clear} error={$httpData.error} />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
<Modal onClose={closeMapHandler} show={showMap} header={props.place.address}>
    <Map
        position={props.place.location}
        zoom={13}
        markerText={props.place.title}
    />
    {#snippet footer()}
        <Button inverse onClick={closeMapHandler}>CLOSE</Button>
    {/snippet}
</Modal>
<Modal
    onClose={closeDeleteModalHandler}
    show={showDeleteModal}
    header="Are you sure?"
>
    <p class="delete-text-messaage">
        Do you want to proceed and delete this place?
    </p>
    {#snippet footer()}
        <Button color="danger" onClick={deleteHandler}>DELETE</Button>
        <Button onClick={closeDeleteModalHandler}>CANCEL</Button>
    {/snippet}
</Modal>
<li class="place-item">
    <div class="card place-item-card">
        <div class="image-container">
            <img src={imageUrl} alt={props.place.title} />
        </div>
        <div class="place-info">
            <h2>{props.place.title}</h2>
            <h2>{props.place.address}</h2>
            <p>{props.place.description}</p>
        </div>
        <div class="place-actions">
            <Button onClick={openMapHandler} color="secondary" inverse>
                VIEW ON MAP
            </Button>
            {#if isUserOwned}
                <Button to={updatePlaceRoute(props.place.id)}>EDIT</Button>
                <Button color="danger" onClick={openDeleteModalHandler}>
                    DELETE
                </Button>
            {/if}
        </div>
    </div>
</li>

<style lang="css">
@reference "@/main.css";

.delete-text-messaage {
    @apply p-5;
}

li.place-item {
    @apply my-4;
}

.place-item-card {
    @apply p-0;
}

.place-item .image-container {
    @apply w-full h-52 md:h-80 mr-6;
}

.place-item-card img {
    @apply w-full h-full object-cover;
}

.place-item .place-info {
    @apply p-4 text-center;
}

.place-item .place-info h2,
.place-item .place-info p {
    @apply mb-2;
}

.place-item .place-actions {
    @apply p-4 text-center border-t border-pen-ruler;
}

.place-item .place-actions :global(.btn) {
    @apply mx-1;
}
</style>

// frontend-vue/src/components/places/PlaceItem.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
    />
    <div v-if="httpData.loading" class="center">
        <LoadingSpinner as-overlay />
    </div>
    <Modal @close="closeMapHandler" :show="showMap" :header="place.address">
        <Map :position="place.location" :zoom="13" :marker-text="place.title" />
        <template #footer>
            <Button inverse @click="closeMapHandler"> CLOSE </Button>
        </template>
    </Modal>
    <Modal
        @close="closeDeleteModalHandler"
        :show="showDeleteModal"
        header="Are you sure?"
    >
        <p class="delete-text-messaage">
            Do you want to proceed and delete this place?
        </p>
        <template #footer>
            <Button color="danger" @click="deleteHandler">DELETE</Button>
            <Button @click="closeDeleteModalHandler">CANCEL</Button>
        </template>
    </Modal>
    <li class="place-item">
        <div class="card place-item-card">
            <div class="image-container">
                <img :src="imageUrl" :alt="place.title" />
            </div>
            <div class="place-info">
                <h2>{{ props.place.title }}</h2>
                <h2>{{ props.place.address }}</h2>
                <p>{{ props.place.description }}</p>
            </div>
            <div class="place-actions">
                <Button @click="openMapHandler" color="secondary" inverse>
                    VIEW ON MAP
                </Button>
                <Button
                    v-if="isUserOwned"
                    :to="updatePlaceRoute(props.place.id)"
                    >EDIT</Button
                >
                <Button
                    v-if="isUserOwned"
                    color="danger"
                    @click="openDeleteModalHandler"
                >
                    DELETE
                </Button>
            </div>
        </div>
    </li>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

import { Button } from "@/components/form";
import { HttpError, LoadingSpinner, Map, Modal } from "@/components/ui";
import { useBackend } from "@/composables";
import { updatePlaceRoute } from "@/router";
import { useAuthStore } from "@/store";
import type { Place } from "@/types";

// Init
const placeholder = "/public/place_placeholder.jpg";
const authStore = useAuthStore();
const { httpData, sendRequest, clear } = useBackend();

// Props
const props = defineProps<{
    place: Place;
}>();

// States
const showMap = ref<boolean>(false);
const showDeleteModal = ref<boolean>(false);

// Computed
const isUserOwned = computed(() => {
    return authStore?.userId === props.place.creator_id;
});

const imageUrl = computed(() => props.place.image_url || placeholder);

// Events
const emit = defineEmits<{
    (e: "delete"): void;
}>();

// Handlers
const openMapHandler = () => {
    showMap.value = true;
};

const closeMapHandler = () => {
    showMap.value = false;
};

const openDeleteModalHandler = () => {
    showDeleteModal.value = true;
};

const closeDeleteModalHandler = () => {
    showDeleteModal.value = false;
};

const deleteHandler = () => {
    closeDeleteModalHandler();
    sendRequest(`/places/${props.place.id}`, "delete").then(() => {
        emit("delete");
    });
};
</script>

<style scoped lang="css">
@reference "@/main.css";

.delete-text-messaage {
    @apply p-5;
}

li.place-item {
    @apply my-4;
}

.place-item-card {
    @apply p-0;
}

.place-item .image-container {
    @apply w-full h-52 md:h-80 mr-6;
}

.place-item-card img {
    @apply w-full h-full object-cover;
}

.place-item .place-info {
    @apply p-4 text-center;
}

.place-item .place-info h2,
.place-item .place-info p {
    @apply mb-2;
}

.place-item .place-actions {
    @apply p-4 text-center border-t border-pen-ruler;
}

.place-item .place-actions button,
.place-item .place-actions a {
    @apply mx-1;
}
</style>
