// frontend-angular/src/components/place/place-create-form/place-create-form.ts
import { Component, inject, signal } from '@angular/core';
import { form, FormRoot, minLength, validate } from '@angular/forms/signals';
import { Router } from '@angular/router';

import { Button, ImageUpload, Input } from '@/components/form';
import { HttpError, LoadingSpinner } from '@/components/ui';
import { AppRoute } from '@/router';
import { BackendService } from '@/services';
import { AuthStore } from '@/store';

interface PlaceCreateFormModel {
    title: string;
    address: string;
    description: string;
    lat: number;
    lng: number;
    image: { file: File | null; url: string };
}

@Component({
    selector: 'app-place-create-form',
    templateUrl: './place-create-form.html',
    styleUrl: './place-create-form.css',
    imports: [Button, Input, ImageUpload, LoadingSpinner, HttpError, FormRoot],
    providers: [BackendService],
})
export class PlaceCreateForm {
    // Init
    private authStore = inject(AuthStore);
    private router = inject(Router);
    backend = inject(BackendService);

    // State
    model = signal<PlaceCreateFormModel>({
        title: '',
        address: '',
        description: '',
        lat: 0,
        lng: 0,
        image: { file: null, url: '' },
    });

    // Form
    placeForm = form(this.model, (path) => {
        minLength(path.title, 10, { message: 'Please enter a valid Title' });
        minLength(path.address, 1, { message: 'Please enter a valid address' });
        minLength(path.description, 10, { message: 'Please enter a valid Description' });

        validate(path.lat, (ctx) =>
            Number.isFinite(ctx.value())
                ? null
                : { kind: 'numeric', message: 'Please enter a valid Latitude' }
        );
        validate(path.lng, (ctx) =>
            Number.isFinite(ctx.value())
                ? null
                : { kind: 'numeric', message: 'Please enter a valid Longitude' }
        );
    });

    // Handlers
    private async submit() {
        const value = this.model();

        const formData = new FormData();
        formData.append('title', value.title);
        formData.append('description', value.description);
        formData.append('address', value.address);
        formData.append('lat', String(value.lat));
        formData.append('lng', String(value.lng));
        formData.append('creator_id', String(this.authStore.userId()));
        if (value.image.file) {
            formData.append('image', value.image.file);
        }

        try {
            await this.backend.sendRequest('/places/', 'post', formData);
            this.router.navigateByUrl(AppRoute.HOME);
        } catch (err) {
            console.log(err);
        }
    }

    onSubmit(e: Event) {
        e.preventDefault();
        this.submit();
    }
}

// frontend-vue/src/components/places/PlaceCreateForm.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
    />
    <LoadingSpinner v-if="httpData.loading" as-overlay />
    <form @submit="submitHandler" class="place-create">
        <Input
            v-model="fields.title.value"
            :is-valid="fields.title.valid"
            id="title"
            element="input"
            type="text"
            label="Title"
            errorText="Please enter a valid Title"
        />
        <Input
            v-model="fields.address.value"
            :is-valid="fields.address.valid"
            id="address"
            element="input"
            type="text"
            label="Address"
            errorText="Please enter a valid address"
        />
        <Input
            v-model="fields.description.value"
            :is-valid="fields.description.valid"
            id="description"
            element="textarea"
            label="Description"
            errorText="Please enter a valid Description"
        />
        <Input
            v-model="fields.lat.value"
            :is-valid="fields.lat.valid"
            class="basis-full sm:basis-1/2 sm:pr-2"
            id="latitude"
            element="input"
            type="number"
            step="any"
            label="Latitude"
            errorText="Please enter a valid Latitude"
        />
        <Input
            v-model="fields.lng.value"
            :is-valid="fields.lng.valid"
            class="basis-full sm:basis-1/2 sm:pl-2"
            id="longitude"
            element="input"
            type="number"
            step="any"
            label="Longitude"
            errorText="Please enter a valid Longitude"
        />
        <ImageUpload
            v-model="fields.image.value"
            :is-valid="fields.image.valid"
            id="image"
            color="secondary"
        />
        <div class="buttons">
            <Button :disabled="!formValid" type="submit" color="secondary">
                Add Place
            </Button>
        </div>
    </form>
</template>

<script setup lang="ts">
import { Button, ImageUpload, Input } from "@/components/form";
import { HttpError, LoadingSpinner } from "@/components/ui";
import type { FormConfig } from "@/composables";
import { useBackend, useForm } from "@/composables";
import { AppRoute, router } from "@/router";
import { useAuthStore } from "@/store";
import { minLengthValidator, numericValidator } from "@/utils";

// Init
const authStore = useAuthStore();
const { httpData, sendRequest, clear } = useBackend();

// Form
const CreatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
    image: { initial: { file: null, url: "" } },
};

type FieldsType = keyof typeof CreatePlaceFormConfig;

const { fields, formValid } = useForm<FieldsType>(CreatePlaceFormConfig);

// Handlers
const submitHandler = async (e: Event) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append("title", fields.title.value);
    formData.append("description", fields.description.value);
    formData.append("address", fields.address.value);
    formData.append("lat", fields.lat.value);
    formData.append("lng", fields.lng.value);
    formData.append("creator_id", authStore.userId as any);
    if (fields.image.value.file) {
        formData.append("image", fields.image.value.file);
    }

    try {
        await sendRequest("/places/", "post", formData);
        router.push(AppRoute.HOME);
    } catch (err) {
        console.log(err);
    }
};
</script>

<style lang="css">
@reference "@/main.css";

.place-create {
    @apply flex flex-wrap;
    @apply relative w-[90%] max-w-160 my-0 mx-auto p-4;
    @apply list-none shadow-md rounded-md bg-surface;
}

.place-create .buttons {
    @apply w-full mt-10 text-right;
}
</style>
