// frontend-svelte/src/components/places/PlaceUpdateForm.svelte
<script lang="ts">
import { goto } from "@mateothegreat/svelte5-router";
import type { AxiosResponse } from "axios";
import { onMount } from "svelte";

import { Button, Input } from "@/components/form";
import { HttpError, LoadingSpinner } from "@/components/ui";
import type { FormConfig } from "@/composables";
import { useBackend, useForm } from "@/composables";
import { AppRoute } from "@/router";
import type { Place } from "@/types";
import { minLengthValidator, numericValidator } from "@/utils";

// Init
const { httpData, sendRequest, clear } = useBackend();

// Props
const props = $props<{ placeId: string }>();

// Form
const UpdatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
};

type FieldsType = keyof typeof UpdatePlaceFormConfig;

const { fields, formValid, prefillData } = useForm<FieldsType>(
    UpdatePlaceFormConfig
);
const { title, address, description, lat, lng } = fields;

// Events
onMount(() => {
    sendRequest(`/places/${props.placeId}`, "get").then(
        (resp: AxiosResponse<Place>) => {
            const { data } = resp;
            prefillData({
                title: data.title,
                address: data.address,
                description: data.description,
                lat: String(data.location.lat),
                lng: String(data.location.lng),
            });
        }
    );
});

// Handlers
const submitHandler = async (e: Event) => {
    e.preventDefault();
    try {
        await sendRequest(`/places/${props.placeId}`, "put", {
            title: $title.value,
            address: $address.value,
            description: $description.value,
            location: {
                lat: $lat.value,
                lng: $lng.value,
            },
        });
        goto(AppRoute.HOME);
    } catch (err) {
        console.log(err);
    }
};
</script>

{#if $httpData.error?.message}
    <HttpError onClose={clear} error={$httpData.error} />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
<form onsubmit={submitHandler} class="place-update">
    <Input
        bind:value={$title.value}
        bind:valid={$title.valid}
        id="title"
        element="input"
        type="text"
        label="Title"
        errorText="Please enter a valid Title"
    />
    <Input
        bind:value={$address.value}
        bind:valid={$address.valid}
        id="address"
        element="input"
        type="text"
        label="Address"
        errorText="Please enter a valid address"
    />
    <Input
        bind:value={$description.value}
        bind:valid={$description.valid}
        id="description"
        element="textarea"
        label="Description"
        errorText="Please enter a valid Description"
    />
    <Input
        bind:value={$lat.value}
        bind:valid={$lat.valid}
        class="basis-full sm:basis-1/2 sm:pr-2"
        id="latitude"
        element="input"
        type="number"
        step="any"
        label="Latitude"
        errorText="Please enter a valid Latitude"
    />
    <Input
        bind:value={$lng.value}
        bind:valid={$lng.valid}
        class="basis-full sm:basis-1/2 sm:pl-2"
        id="longitude"
        element="input"
        type="number"
        step="any"
        label="Longitude"
        errorText="Please enter a valid Longitude"
    />
    <div class="buttons">
        <Button disabled={!$formValid} type="submit" color="secondary">
            Edit Place
        </Button>
    </div>
</form>

<style lang="css">
@reference "@/main.css";

.place-update {
    @apply flex flex-wrap;
    @apply relative w-[90%] max-w-160 my-0 mx-auto p-4;
    @apply list-none shadow-md rounded-md bg-surface;
}

.place-update .buttons {
    @apply w-full mt-10 text-right;
}
</style>

// frontend-vue/src/components/places/PlaceUpdateForm.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
    />
    <LoadingSpinner v-else-if="httpData.loading" as-overlay />
    <form @submit="submitHandler" class="place-update">
        <Input
            v-model="fields.title.value"
            :is-valid="fields.title.valid"
            id="title"
            element="input"
            type="text"
            label="Title"
            errorText="Please enter a valid Title"
        />
        <Input
            v-model="fields.address.value"
            :is-valid="fields.address.valid"
            id="address"
            element="input"
            type="text"
            label="Address"
            errorText="Please enter a valid address"
        />
        <Input
            v-model="fields.description.value"
            :is-valid="fields.description.valid"
            id="description"
            element="textarea"
            label="Description"
            errorText="Please enter a valid Description"
        />
        <Input
            v-model="fields.lat.value"
            :is-valid="fields.lat.valid"
            class="basis-full sm:basis-1/2 sm:pr-2"
            id="latitude"
            element="input"
            type="number"
            step="any"
            label="Latitude"
            errorText="Please enter a valid Latitude"
        />
        <Input
            v-model="fields.lng.value"
            :is-valid="fields.lng.valid"
            class="basis-full sm:basis-1/2 sm:pl-2"
            id="longitude"
            element="input"
            type="number"
            step="any"
            label="Longitude"
            errorText="Please enter a valid Longitude"
        />
        <div class="buttons">
            <Button :disabled="!formValid" type="submit" color="secondary">
                Edit Place
            </Button>
        </div>
    </form>
</template>

<script setup lang="ts">
import type { AxiosResponse } from "axios";
import { onMounted } from "vue";

import { Button, Input } from "@/components/form";
import { HttpError, LoadingSpinner } from "@/components/ui";
import type { FormConfig } from "@/composables";
import { useBackend, useForm } from "@/composables";
import { AppRoute, router } from "@/router";
import type { Place } from "@/types";
import { minLengthValidator, numericValidator } from "@/utils";

// Init
const { httpData, sendRequest, clear } = useBackend();

// Props
const props = defineProps<{ placeId: string }>();

// Form
const UpdatePlaceFormConfig: FormConfig = {
    title: { validators: [minLengthValidator(10)] },
    address: { validators: [minLengthValidator(1)] },
    description: { validators: [minLengthValidator(10)] },
    lat: { validators: [numericValidator()] },
    lng: { validators: [numericValidator()] },
};

type FieldsType = keyof typeof UpdatePlaceFormConfig;

const { fields, formValid, prefillData } = useForm<FieldsType>(
    UpdatePlaceFormConfig
);

// Events
onMounted(() => {
    sendRequest(`/places/${props.placeId}`, "get").then(
        (resp: AxiosResponse<Place>) => {
            const { data } = resp;
            prefillData({
                title: data.title,
                address: data.address,
                description: data.description,
                lat: String(data.location.lat),
                lng: String(data.location.lng),
            });
        }
    );
});

// Handlers
const submitHandler = async (e: Event) => {
    e.preventDefault();
    try {
        await sendRequest(`/places/${props.placeId}`, "put", {
            title: fields.title.value,
            address: fields.address.value,
            description: fields.description.value,
            location: {
                lat: fields.lat.value,
                lng: fields.lng.value,
            },
        });
        router.push(AppRoute.HOME);
    } catch (err) {
        console.log(err);
    }
};
</script>

<style lang="css">
@reference "@/main.css";

.place-update {
    @apply flex flex-wrap;
    @apply relative w-[90%] max-w-160 my-0 mx-auto p-4;
    @apply list-none shadow-md rounded-md bg-surface;
}

.place-update .buttons {
    @apply w-full mt-10 text-right;
}
</style>
