// frontend-vue/src/pages/Users.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
        header="Could not fetch users!"
    />
    <LoadingSpinner v-if="httpData.loading" as-overlay />
    <UsersList v-if="items.length" :items="items" />
</template>

<script setup lang="ts">
import { computed, onMounted } from "vue";

import { HttpError, LoadingSpinner } from "@/components/ui";
import { UsersList } from "@/components/user";
import { useHttp } from "@/lib";
import type { User } from "@/types";

// Init
const { httpData, sendRequest, clear } = useHttp();

// Computed
const items = computed((): User[] => {
    if (httpData.value.json?.data) {
        return httpData.value.json?.data as User[];
    }
    return [];
});

// Events
onMounted(() => {
    sendRequest("/users/", "get");
});
</script>

// frontend-svelte/src/pages/Users.svelte
<script lang="ts">
import { onMount } from "svelte";

import { HttpError, LoadingSpinner } from "@/components/ui";
import { UsersList } from "@/components/user";
import { useHttp } from "@/lib";
import type { User } from "@/types";

// Init
const { httpData, sendRequest, clear } = useHttp();

// Computed
let items = $derived<User[]>($httpData.json?.data ?? []);

// Events
onMount(() => {
    sendRequest("/users/", "get");
});
</script>

{#if $httpData.error?.message}
    <HttpError
        onClose={clear}
        error={$httpData.error}
        header="Could not fetch users!"
    />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
{#if items.length}
    <UsersList {items} />
{/if}
