// frontend-react/src/pages/UserPlaces.tsx
import { HttpStatusCode } from "axios";
import { useCallback, useEffect } from "react";
import { useParams } from "react-router-dom";

import { PlacesList } from "@/components/places";
import { HttpError, LoadingSpinner } from "@/components/ui";
import { useHttp } from "@/hooks";
import { useAppSelector } from "@/store";
import type { Place } from "@/types";

const UserPlaces: React.FC = () => {
    const authData = useAppSelector((state) => state.auth.data);
    const [data, sendRequest, clearError] = useHttp({ ignoreNotFound: true });
    const { userId } = useParams();

    const isSameUser = Number(userId) === authData?.user_id ? true : false;

    const fetchPlaces = useCallback(
        async (userId: string | undefined) => {
            if (!userId) {
                return;
            }

            try {
                await sendRequest(`/places/?creator_id=${userId}`, "get");
            } catch (err) {
                console.log(err);
            }
        },
        [sendRequest]
    );

    useEffect(() => {
        fetchPlaces(userId);
    }, [fetchPlaces, userId]);

    const onDelete = () => {
        fetchPlaces(userId);
    };

    const renderPlaces = (): React.JSX.Element | undefined => {
        if (!data.loading && data.json?.data) {
            let places = (data.json.data as Place[]) || [];
            if (data.statusCode === HttpStatusCode.NotFound) {
                places = [];
            }
            return (
                <PlacesList
                    sameAuthenticatedUser={isSameUser}
                    items={places}
                    onDelete={onDelete}
                />
            );
        }
    };

    return (
        <>
            {data.error?.message && (
                <HttpError error={data.error} onClear={clearError} />
            )}
            {data.loading && <LoadingSpinner asOverlay />}
            {renderPlaces()}
        </>
    );
};

export default UserPlaces;

// frontend-svelte/src/pages/UserPlaces.svelte
<script lang="ts">
import { HttpStatusCode } from "axios";
import { onMount } from "svelte";

import { PlacesList } from "@/components/places";
import { HttpError, LoadingSpinner } from "@/components/ui";
import { useHttp } from "@/lib";
import { authStore } from "@/store";
import type { Place } from "@/types";

// Init
const { route } = $props();
const userId: number = Number(route.result.path.params.userId);
const { httpData, sendRequest, clear } = useHttp({ ignoreNotFound: true });
const loggedUserId = authStore.userId;

// Events
onMount(() => {
    fetchPlaces(userId);
});

// Computed
const isUserOwned = $derived<boolean>(userId === $loggedUserId);

const places = $derived<Place[]>(
    $httpData.statusCode === HttpStatusCode.NotFound
        ? []
        : $httpData.json?.data || []
);

// Handlers
const fetchPlaces = (userId: number | undefined) => {
    if (!userId) return;
    sendRequest(`/places/?creator_id=${userId}`, "get").catch((err) =>
        console.log(err)
    );
};

const deleteHandler = async () => {
    fetchPlaces(userId);
};
</script>

{#if $httpData.error?.message}
    <HttpError onClose={clear} error={$httpData.error} />
{/if}
{#if $httpData.loading}
    <LoadingSpinner asOverlay />
{/if}
<PlacesList
    onDelete={deleteHandler}
    items={places}
    sameAuthenticatedUser={isUserOwned}
/>
