// frontend-vue/src/pages/UserPlaces.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
    />
    <LoadingSpinner v-if="httpData.loading" as-overlay />
    <PlacesList
        @delete="deleteHandler"
        :items="places"
        :same-authenticated-user="isUserOwned"
    />
</template>

<script setup lang="ts">
import { HttpStatusCode } from "axios";
import { computed, watch } from "vue";
import { useRoute } from "vue-router";

import { PlacesList } from "@/components/places";
import { HttpError, LoadingSpinner } from "@/components/ui";
import { useBackend } from "@/composables";
import { useAuthStore } from "@/store";
import type { Place } from "@/types";

// Init
const authStore = useAuthStore();
const route = useRoute();
const { httpData, sendRequest, clear } = useBackend({ ignoreNotFound: true });

// Computed
const userId = computed(() => Number(route.params.userId) || undefined);
const isUserOwned = computed(() => {
    return userId.value === authStore.userId;
});

const places = computed(() => {
    let result = (httpData.value.json?.data as Place[]) || [];
    if (httpData.value.statusCode === HttpStatusCode.NotFound) result = [];
    return result;
});

// Handlers
const fetchPlaces = (userId: number | undefined) => {
    if (!userId) return;
    sendRequest(`/places/?creator_id=${userId}`, "get").catch((err) =>
        console.log(err)
    );
};

const deleteHandler = async () => {
    fetchPlaces(userId.value);
};

// Watchers
watch(userId, fetchPlaces, { immediate: true });
</script>

// frontend-angular/src/pages/user-places/user-places.ts
import { Component, computed, effect, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute } from '@angular/router';
import { HttpStatusCode } from 'axios';

import { PlacesList } from '@/components/place';
import { HttpError, LoadingSpinner } from '@/components/ui';
import { BackendService } from '@/services';
import { AuthStore } from '@/store';
import type { Place } from '@/types';

@Component({
    selector: 'app-user-places',
    templateUrl: './user-places.html',
    imports: [PlacesList, HttpError, LoadingSpinner],
})
export class UserPlaces {
    // Init
    authStore = inject(AuthStore);
    backend = inject(BackendService);
    route = inject(ActivatedRoute);
    private params = toSignal(this.route.params);

    // Computed
    userId = computed(() => Number(this.params()?.['userId']) || undefined);

    isUserOwned = computed(() => this.userId() === this.authStore.userId());

    places = computed((): Place[] => {
        const data = this.backend.httpData().json?.data as Place[];
        if (this.backend.httpData().statusCode === HttpStatusCode.NotFound) return [];
        return data || [];
    });

    // Handlers
    private fetchPlaces() {
        const userId = this.userId();
        if (!userId) return;
        this.backend.sendRequest(`/places/?creator_id=${userId}`, 'get').catch(console.error);
    }

    private onUserIdUpdate = effect(() => {
        this.fetchPlaces();
    });

    deleteHandler() {
        this.fetchPlaces();
    }
}
