// frontend-react/src/components/user/AuthForm.tsx
import { useState } from "react";

import type { FormConfig } from "@/lib";
import { emailValidator, minLengthValidator, useForm, useHttp } from "@/lib";
import { authSlice, useAppDispatch } from "@/store";
import type { SigninResponse } from "@/types";

import { Button, ImageUpload, Input } from "../form";
import { HttpError, LoadingSpinner } from "../ui";

const AuthFormConfig: FormConfig = {
    username: { active: false, validators: [minLengthValidator(8)] },
    image: { active: false, initial: { file: null, url: "" } },
    email: { validators: [emailValidator()] },
    password: { validators: [minLengthValidator(10)] },
};

type FieldsType = keyof typeof AuthFormConfig;

const AuthForm: React.FC = () => {
    const dispatch = useAppDispatch();

    const [data, sendRequest, clearError] = useHttp();
    const [isLoginMode, setIsLoginMode] = useState(true);
    const [state, inputHandlers, , updateFieldConfig] =
        useForm<FieldsType>(AuthFormConfig);

    // Text to display depending if Signin form or Signup form
    let verb: "Authenticate" | "Register";
    let requiredText: "Login Required" | "Registration Required";
    let switchText: "Swith to login" | "Switch to signup";
    if (isLoginMode) {
        verb = "Authenticate";
        requiredText = "Login Required";
        switchText = "Switch to signup";
    } else {
        verb = "Register";
        requiredText = "Registration Required";
        switchText = "Swith to login";
    }

    const onSignin = async (): Promise<void> => {
        // use URLSearchParams for application/x-www-form-urlencoded
        const body = new URLSearchParams();
        body.append("username", state.fields.email.value);
        body.append("password", state.fields.password.value);
        const resp = await sendRequest("/auth/signin", "post", body, false);
        const data = resp.data as SigninResponse;
        dispatch(authSlice.actions.login(data));
    };

    const onSignup = async (): Promise<void> => {
        // use FormData for multipart/form-data
        const formData = new FormData();
        formData.append("name", state.fields.username.value);
        formData.append("email", state.fields.email.value);
        formData.append("password", state.fields.password.value);
        if (state.fields.image.value.file) {
            formData.append("image", state.fields.image.value.file);
        }
        const resp = await sendRequest("/auth/signup", "post", formData, false);
        const data = resp.data as SigninResponse;
        dispatch(authSlice.actions.login(data));
    };

    const onSubmit = (e: React.FormEvent): void => {
        e.preventDefault();
        if (isLoginMode) {
            onSignin();
        } else {
            onSignup();
        }
    };

    const onSwitchModeHandler = () => {
        setIsLoginMode((prev: boolean) => {
            // if prev === true ==> We were in Login Mode
            // username and image were disabled (false)
            // Switching to Signup Mode, we want to
            // enable them so we send prev (true)
            // Same reasoning if we were in Signup Mode
            updateFieldConfig({
                username: { active: prev },
                image: { active: prev },
            });
            return !prev;
        });
    };

    return (
        <div className="center">
            {data.error?.message && (
                <HttpError
                    header="Credentials not valid!"
                    error={data.error}
                    onClear={() => clearError()}
                />
            )}
            <div className="auth-form">
                {data.loading && <LoadingSpinner asOverlay />}
                <h2>{requiredText}</h2>
                <hr />
                <form onSubmit={onSubmit}>
                    {!isLoginMode && (
                        <Input
                            onInput={inputHandlers.username}
                            value={state.fields.username.value}
                            isValid={state.fields.username.valid}
                            element="input"
                            id="username"
                            type="text"
                            label="Username"
                            errorText="Please enter a valid username of at least 8 characters"
                        />
                    )}
                    {!isLoginMode && (
                        <ImageUpload
                            onInput={inputHandlers.image}
                            value={state.fields.image.value}
                            isValid={state.fields.image.valid}
                            id="image"
                            buttonText="Upload your Avatar"
                            color="secondary"
                            errorText="Please upload a valid image"
                        />
                    )}
                    <Input
                        onInput={inputHandlers.email}
                        value={state.fields.email.value}
                        isValid={state.fields.email.valid}
                        element="input"
                        id="email"
                        type="email"
                        label="E-Mail"
                        errorText="Please enter a valid email"
                    />
                    <Input
                        onInput={inputHandlers.password}
                        value={state.fields.password.value}
                        isValid={state.fields.password.valid}
                        element="input"
                        id="password"
                        type="password"
                        label="Password"
                        errorText="Please enter a password with at least 10 characters"
                    />
                    <div className="buttons">
                        <Button
                            color="secondary"
                            disabled={!state.valid}
                            type="submit"
                        >
                            {verb}
                        </Button>
                        <Button
                            type="button"
                            color="secondary"
                            inverse
                            onClick={onSwitchModeHandler}
                        >
                            {switchText}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default AuthForm;

// frontend-svelte/src/components/user/AuthForm.svelte
<script lang="ts">
import { SvelteURLSearchParams } from "svelte/reactivity";

import { Button, ImageUpload, Input } from "@/components/form";
import { HttpError, LoadingSpinner } from "@/components/ui";
import type { FormConfig } from "@/lib";
import { emailValidator, minLengthValidator, useForm, useHttp } from "@/lib";
import { authStore } from "@/store";
import type { SigninResponse } from "@/types";

// Init
const { httpData, sendRequest, clear } = useHttp();

// Form
const AuthFormConfig: FormConfig = {
    username: { active: false, validators: [minLengthValidator(8)] },
    image: { active: false, initial: { file: null, url: "" } },
    email: { validators: [emailValidator()] },
    password: { validators: [minLengthValidator(10)] },
};

type FieldsType = keyof typeof AuthFormConfig;

const { fields, formValid, updateFieldConfig } =
    useForm<FieldsType>(AuthFormConfig);
const { username, image, email, password } = fields;

// States
let isLoginMode = $state<boolean>(true);

// Computed
const text = $derived(
    isLoginMode
        ? {
              verb: "Authenticate",
              requiredText: "Login Required",
              switchText: "Switch to signup",
          }
        : {
              verb: "Register",
              requiredText: "Registration Required",
              switchText: "Swith to login",
          }
);

// Handlers
const onSignin = async (): Promise<void> => {
    // use URLSearchParams for application/x-www-form-urlencoded
    const body = new SvelteURLSearchParams();
    body.append("username", $email.value);
    body.append("password", $password.value);
    const resp = await sendRequest("/auth/signin", "post", body, false);
    const data = resp.data as SigninResponse;
    authStore.login(data);
};

const onSignup = async (): Promise<void> => {
    // use FormData for multipart/form-data
    const formData = new FormData();
    formData.append("name", $username.value);
    formData.append("email", $email.value);
    formData.append("password", $password.value);
    if ($image.value.file) {
        formData.append("image", $image.value.file);
    }
    const resp = await sendRequest("/auth/signup", "post", formData, false);
    const data = resp.data as SigninResponse;
    authStore.login(data);
};

const onSubmit = (e: Event): void => {
    e.preventDefault();
    if (isLoginMode) {
        onSignin();
    } else {
        onSignup();
    }
};

const onSwitchModeHandler = () => {
    // if prev === true ==> We were in Login Mode
    // username and image were disabled (false)
    // Switching to Signup Mode, we want to
    // enable them so we send prev (true)
    // Same reasoning if we were in Signup Mode
    const prev = isLoginMode;
    updateFieldConfig({ username: { active: prev }, image: { active: prev } });
    isLoginMode = !prev;
};
</script>

<div class="center">
    {#if $httpData.error?.message}
        <HttpError
            onClose={clear}
            error={$httpData.error}
            header="Credentials not valid!"
        />
    {/if}
    <div class="auth-form">
        {#if $httpData.loading}
            <LoadingSpinner asOverlay />
        {/if}
        <h2>{text.requiredText}</h2>
        <hr />
        <form onsubmit={onSubmit}>
            {#if !isLoginMode}
                <Input
                    bind:value={$username.value}
                    bind:valid={$username.valid}
                    element="input"
                    id="username"
                    label="Username"
                    type="text"
                    errorText="Please enter a valid username of at least 8 characters"
                />
                <ImageUpload
                    bind:value={$image.value}
                    bind:valid={$image.valid}
                    id="image"
                    color="secondary"
                    buttonText="Upload your Avatar"
                    errorText="Please upload a valid image"
                />
            {/if}
            <Input
                bind:value={$email.value}
                bind:valid={$email.valid}
                element="input"
                id="email"
                label="E-mail"
                type="email"
                errorText="Please enter a valid email"
            />
            <Input
                bind:value={$password.value}
                bind:valid={$password.valid}
                element="input"
                id="password"
                label="Password"
                type="password"
                errorText="Please enter a password with at least 10 characters"
            />
            <div class="buttons">
                <Button
                    class="auth-button"
                    disabled={!$formValid}
                    color="secondary"
                    type="submit"
                >
                    {text.verb}
                </Button>
                <Button
                    class="auth-button"
                    onClick={onSwitchModeHandler}
                    type="button"
                    color="secondary"
                    inverse
                >
                    {text.switchText}
                </Button>
            </div>
        </form>
    </div>
</div>

<style lang="css">
@reference "@/main.css";

.auth-form {
    @apply w-[90%] max-w-md mx-auto mt-10 p-6;
    @apply text-center shadow-lg rounded-xl bg-surface;
}

.auth-form > h2 {
    @apply text-2xl font-bold text-pen mb-2;
}

.auth-form > hr {
    @apply border-t-2 border-secondary w-[100%] mb-6;
}

.auth-form .buttons {
    @apply flex justify-center space-x-4;
}

.auth-form .buttons :global(.auth-button) {
    @apply min-w-40;
}
</style>
