// frontend-vue/src/components/user/UsersList.vue
<template>
    <div v-if="noUsers" class="no-users">
        <div class="card">
            <h2>No Users found!</h2>
        </div>
    </div>
    <ul v-else class="users-list">
        <UserItem v-for="item in props.items" :key="item.id" :user="item" />
    </ul>
</template>

<script setup lang="ts">
import { computed } from "vue";

import type { User } from "@/types";

import { UserItem } from "./";

// Props
const props = defineProps<{
    items: User[];
}>();

// Computed
const noUsers = computed(() => props.items.length === 0);
</script>

<style lang="css">
@reference "@/main.css";

.users-list {
    @apply flex flex-wrap gap-6;
    @apply w-[90%] max-w-4xl mx-auto;
}

.no-users {
    @apply flex justify-center items-center;
}

.no-users h2 {
    @apply text-xl font-semibold text-pen;
}
</style>

// frontend-svelte/src/components/user/UsersList.svelte
<script lang="ts">
import type { User } from "@/types";

import UserItem from "./UserItem.svelte";

// Props
const props = $props<{ items: User[] }>();
const items: User[] = props.items;

// Computed
const noUsers = $derived<boolean>(items.length === 0);
</script>

{#if noUsers}
    <div class="no-users">
        <div class="card">
            <h2>No Users found!</h2>
        </div>
    </div>
{:else}
    <div class="users-list">
        {#each items as item (item.id)}
            <UserItem user={item} />
        {/each}
    </div>
{/if}

<style lang="css">
@reference "@/main.css";

.users-list {
    @apply flex flex-wrap gap-6;
    @apply w-[90%] max-w-4xl mx-auto;
}

.no-users {
    @apply flex justify-center items-center;
}

.no-users h2 {
    @apply text-xl font-semibold text-pen;
}
</style>
