// frontend-react/src/pages/Users.tsx
import { useEffect } from "react";

import { HttpError, LoadingSpinner } from "../components/ui";
import { UsersList } from "../components/user";
import { useHttp } from "../lib";
import { User } from "../types";

const Users: React.FC = () => {
    const [data, sendRequest, clearError] = useHttp();

    useEffect(() => {
        sendRequest("/users/", "get", undefined, false);
    }, [sendRequest]);

    return (
        <>
            {data.error?.message && (
                <HttpError
                    header="Could not fetch users!"
                    error={data.error}
                    onClear={() => clearError()}
                />
            )}
            {data.loading && <LoadingSpinner asOverlay />}
            {data.json?.data && <UsersList items={data.json.data as User[]} />}
        </>
    );
};

export default Users;

// frontend-vue/src/views/Users.vue
<template>
    <HttpError
        v-if="httpData.error?.message"
        @close="clear"
        :error="httpData.error"
        header="Could not fetch users!"
    />
    <LoadingSpinner v-if="httpData.loading" as-overlay />
    <UsersList v-if="httpData.json?.data" :items="items" />
</template>

<script setup lang="ts">
import { computed } from "vue";

import { HttpError, LoadingSpinner } from "@/components/ui";
import { UsersList } from "@/components/user";
import { useHttp } from "@/lib";
import { User } from "@/types";

const { httpData, sendRequest, clear } = useHttp();
sendRequest("/users/", "get");

// Computed
const items = computed((): User[] => {
    if (httpData.value.json?.data) {
        return httpData.value.json?.data as User[];
    }
    return [];
});
</script>
