// frontend-angular/src/components/navigation/main-navigation/main-navigation.ts
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

import { Backdrop } from '@/components/ui';
import { AppRoute } from '@/router';
import { AuthStore } from '@/store';

import { NavLinks } from '../nav-links/nav-links';
import { SideDrawer } from '../side-drawer/side-drawer';

@Component({
    selector: 'app-main-navigation',
    templateUrl: './main-navigation.html',
    styleUrl: './main-navigation.css',
    imports: [RouterLink, Backdrop, SideDrawer, NavLinks],
})
export class MainNavigation {
    store = inject(AuthStore);
    AppRoute = AppRoute;
    drawerIsOpen = signal(false);
}

// frontend-react/src/components/navigation/MainNavigation.tsx
import "./MainNavigation.css";

import React, { useState } from "react";
import { Link } from "react-router-dom";

import { AppRoute } from "@/router";

import { useAppSelector } from "../../store";
import Backdrop from "../ui/Backdrop";
import NavLinks from "./NavLinks";
import SideDrawer from "./SideDrawer";

const MainNavigation: React.FC = () => {
    const [drawerIsOpen, setDrawerIsOpen] = useState(false);

    const authData = useAppSelector((state) => state.auth.data);
    const isLoggedIn = !!authData;

    const openDrawer = (): void => {
        setDrawerIsOpen(true);
    };

    const closeDrwaer = (): void => {
        setDrawerIsOpen(false);
    };

    return (
        <>
            {drawerIsOpen && <Backdrop onClick={closeDrwaer} />}
            <SideDrawer show={drawerIsOpen} onClick={closeDrwaer}>
                <nav className="sidedrawer">
                    <NavLinks />
                </nav>
            </SideDrawer>
            <header className="main-header">
                <div>
                    {isLoggedIn && (
                        <button className="hamburger" onClick={openDrawer}>
                            <span />
                            <span />
                            <span />
                        </button>
                    )}
                    <h1 className="app-header">
                        <Link to={AppRoute.HOME}>Your Places</Link>
                    </h1>
                    {isLoggedIn && (
                        <nav className="main">
                            <NavLinks />
                        </nav>
                    )}
                </div>
            </header>
        </>
    );
};

export default MainNavigation;
