// frontend-vue/src/components/navigation/MainNavigation.vue
<template>
    <Backdrop v-if="drawerIsOpen" @click="closeDrawer" />
    <SideDrawer @click="closeDrawer" :show="drawerIsOpen">
        <nav class="sidedrawer">
            <NavLinks />
        </nav>
    </SideDrawer>
    <header class="main-header">
        <div>
            <button
                v-if="authStore.isLoggedIn"
                @click="openDrawer"
                class="hamburger"
            >
                <span />
                <span />
                <span />
            </button>
            <h1 class="app-header">
                <RouterLink :to="AppRoute.HOME">Your Places</RouterLink>
            </h1>
            <nav v-if="authStore.isLoggedIn" class="main">
                <NavLinks />
            </nav>
        </div>
    </header>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { RouterLink } from "vue-router";

import { Backdrop } from "@/components/ui";
import { AppRoute } from "@/router/routes.ts";
import { useAuthStore } from "@/store";

import NavLinks from "./NavLinks.vue";
import SideDrawer from "./SideDrawer.vue";

// Init
const authStore = useAuthStore();

// State
const drawerIsOpen = ref<boolean>(false);

// Hanlders
const openDrawer = () => {
    drawerIsOpen.value = true;
};

const closeDrawer = () => {
    drawerIsOpen.value = false;
};
</script>

<style scoped lang="css">
@reference "@/main.css";

.main-header {
    @apply flex fixed z-50 top-0 left-0;
    @apply w-full h-16 px-4 shadow-md;
    @apply bg-primary;
}

.main-header > div {
    @apply flex items-center w-full max-w-7xl mx-auto;
    @apply bg-transparent;
}

nav.main {
    @apply hidden md:block ml-auto;
}

nav.sidedrawer {
    @apply h-full;
}

h1.app-header {
    @apply text-2xl font-bold text-pen-inverse;
}

button.hamburger {
    @apply flex flex-col justify-around md:hidden;
    @apply w-12 h-12 mr-8 border-none bg-transparent cursor-pointer;
}

button.hamburger span {
    @apply block w-12 h-1 bg-surface;
}
</style>

// frontend-react/src/components/navigation/MainNavigation.tsx
import "./MainNavigation.css";

import React, { useState } from "react";
import { Link } from "react-router-dom";

import { AppRoute } from "@/router";

import { useAppSelector } from "../../store";
import Backdrop from "../ui/Backdrop";
import NavLinks from "./NavLinks";
import SideDrawer from "./SideDrawer";

const MainNavigation: React.FC = () => {
    const [drawerIsOpen, setDrawerIsOpen] = useState(false);

    const authData = useAppSelector((state) => state.auth.data);
    const isLoggedIn = !!authData;

    const openDrawer = (): void => {
        setDrawerIsOpen(true);
    };

    const closeDrwaer = (): void => {
        setDrawerIsOpen(false);
    };

    return (
        <>
            {drawerIsOpen && <Backdrop onClick={closeDrwaer} />}
            <SideDrawer show={drawerIsOpen} onClick={closeDrwaer}>
                <nav className="sidedrawer">
                    <NavLinks />
                </nav>
            </SideDrawer>
            <header className="main-header">
                <div>
                    {isLoggedIn && (
                        <button className="hamburger" onClick={openDrawer}>
                            <span />
                            <span />
                            <span />
                        </button>
                    )}
                    <h1 className="app-header">
                        <Link to={AppRoute.HOME}>Your Places</Link>
                    </h1>
                    {isLoggedIn && (
                        <nav className="main">
                            <NavLinks />
                        </nav>
                    )}
                </div>
            </header>
        </>
    );
};

export default MainNavigation;
