// frontend-react/src/components/user/UsersList.tsx
import { Card } from "../../components/ui";
import { User } from "../../types";
import UserItem from "./UserItem";

interface UserListProps {
    items: User[];
}

const UsersList: React.FC<UserListProps> = ({ items }) => {
    if (items.length === 0) {
        return (
            <div className="flex justify-center items-center">
                <Card>
                    <h2 className="text-xl font-semibold text-gray-700">
                        No Users found!
                    </h2>
                </Card>
            </div>
        );
    }
    return (
        <ul className="w-[90%] max-w-4xl mx-auto flex justify-center flex-wrap gap-6">
            {items.map((item: User) => {
                return <UserItem key={item.id} user={item} />;
            })}
        </ul>
    );
};

export default UsersList;

// frontend-vue/src/components/user/UsersList.vue
<template>
    <div v-if="noUsers" class="no-users">
        <div class="card">
            <h2>No Users found!</h2>
        </div>
    </div>
    <ul v-else class="users-list">
        <UserItem v-for="item in props.items" :key="item.id" :user="item" />
    </ul>
</template>

<script setup lang="ts">
import { computed } from "vue";

import { User } from "@/types";

import { UserItem } from "./";

// Props
const props = defineProps<{
    items: User[];
}>();

// Computed
const noUsers = computed(() => props.items.length === 0);
</script>

<style lang="css">
@reference "../../main.css";

@layer components {
    .users-list {
        @apply flex justify-center flex-wrap gap-6;
        @apply w-[90%] max-w-4xl mx-auto;
    }

    .no-users {
        @apply flex justify-center items-center;
    }

    .no-users h2 {
        @apply text-xl font-semibold text-pen;
    }
}
</style>
