// frontend-svelte/src/components/ui/Avatar.svelte
<script lang="ts">
// Props
const { imageUrl, alt } = $props<{ imageUrl: string; alt: string }>();
</script>

<div class="avatar-container">
    <img src={imageUrl} {alt} />
</div>

<style lang="css">
@reference "@/main.css";

.avatar-container {
    @apply w-16 h-16 overflow-hidden rounded-full;
    @apply flex justify-center items-center;
}

.avatar-container img {
    @apply w-full h-full object-cover;
}
</style>

// frontend-react/src/components/ui/Avatar.tsx
interface AvatarProps {
    className?: string;
    imageUrl: string;
    alt: string;
}

const Avatar: React.FC<AvatarProps> = (props) => {
    return (
        <div
            className={`flex justify-center items-center rounded-full overflow-hidden w-16 h-16 ${props.className || ""}`}
        >
            <img
                src={props.imageUrl}
                alt={props.alt}
                className="w-full h-full object-cover"
            />
        </div>
    );
};

export default Avatar;
