// frontend-vue/src/components/ui/HttpError.vue
<template>
    <Modal
        v-if="isTokenExpired"
        @close="props.onClear"
        header="Session expired"
        :show="!!props.error"
    >
        <p>Token expired! Please login again!</p>
        <template #footer>
            <Button :onClick="tokenExpiredCleaner">Authenticate</Button>
        </template>
    </Modal>
    <ErrorModal
        v-else-if="props.error"
        :error="props.error.message"
        :header="props.header"
        :onClear="props.onClear"
    />
</template>

<script setup lang="ts">
import { AxiosResponse } from "axios";
import { computed } from "vue";

import { Button } from "@/components/form";
import { useAuthStore } from "@/stores";

import ErrorModal from "./ErrorModal.vue";
import Modal from "./Modal.vue";

const authStore = useAuthStore();

// Props
const props = defineProps<{
    error?: {
        tokenExpired?: boolean;
        message?: string;
        response?: AxiosResponse;
    };
    onClear: () => void;
    header?: string;
}>();

// Computed
const isTokenExpired = computed(() => {
    return props.error?.tokenExpired;
});

// Handlers
const tokenExpiredCleaner = () => {
    props.onClear();
    authStore.logout();
};
</script>

// frontend-react/src/components/ui/HttpError.tsx
import { AxiosResponse } from "axios";

import { authSlice, useAppDispatch } from "../../stores";
import { Button } from "../form";
import ErrorModal from "./ErrorModal";
import Modal from "./Modal";

interface HttpErrorProps {
    error: {
        tokenExpired?: boolean;
        message: string;
        response?: AxiosResponse;
    };
    onClear: () => void;
    header?: string;
}

const HttpError: React.FC<HttpErrorProps> = ({ error, onClear, header }) => {
    const dispatch = useAppDispatch();

    const tokenExpiredCleaner = () => {
        onClear();
        dispatch(authSlice.actions.logout());
    };

    if (!error.tokenExpired) {
        return (
            <ErrorModal
                error={error.message}
                header={header}
                onClear={onClear}
            />
        );
    }

    return (
        <Modal
            onCancel={tokenExpiredCleaner}
            header="Session Expired"
            show={!!error}
            footer={<Button onClick={tokenExpiredCleaner}>Authenticate</Button>}
        >
            <p>Token expired! Please login again!</p>
        </Modal>
    );
};

export default HttpError;
