// frontend-svelte/src/components/ui/Map.svelte
<script lang="ts">
import type { Map as LeafletMap, Marker } from "leaflet";
import * as L from "leaflet";
import { onMount } from "svelte";

import type { Location } from "@/types";

// Init
let mapDiv: HTMLDivElement;
let map: LeafletMap;
let marker: Marker;

// Props
const { position, zoom, markerText } = $props<{
    position: Location;
    zoom: number;
    markerText: string;
}>();

// Events
onMount(() => {
    map = L.map(mapDiv).setView([position.lat, position.lng], zoom);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
            '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);
    marker = L.marker([position.lat, position.lng])
        .addTo(map)
        .bindPopup(markerText);

    map.invalidateSize();
    return () => map.remove();
});

// Effects
$effect(() => {
    if (map && marker) {
        marker.setLatLng([position.lat, position.lng]);
        map.setView([position.lat, position.lng], zoom);
    }
});
</script>

<div bind:this={mapDiv} class="map-container"></div>

<style lang="css">
@reference "@/main.css";

.map-container {
    @apply w-full h-50;
}
</style>

// frontend-react/src/components/ui/Map.tsx
import "leaflet/dist/leaflet.css";

import { Map as MapObject } from "leaflet";
import { useEffect, useState } from "react";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";

import { Location } from "../../types";

interface MapProps {
    position: Location;
    zoom: number;
    markerText: string;
}

const Map: React.FC<MapProps> = ({ position, zoom, markerText }) => {
    const [map, setMap] = useState<MapObject | null>(null);

    useEffect(() => {
        if (map) {
            map.invalidateSize();
        }
    }, [map]);

    return (
        <div className="map-container">
            <MapContainer
                center={position}
                zoom={zoom}
                scrollWheelZoom={false}
                className="w-full h-full"
                whenReady={() => setMap}
            >
                <TileLayer
                    attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                />
                <Marker position={position}>
                    <Popup>{markerText}</Popup>
                </Marker>
            </MapContainer>
        </div>
    );
};

export default Map;
