// frontend-vue/src/components/ui/Modal.vue
<template>
    <Teleport to="#modal-hook">
        <Backdrop v-if="props.show" @click="props.onCancel" />
        <Transition name="modal-transition" appear>
            <div v-if="props.show" class="modal-container" :style="style">
                <header>
                    <h2>{{ props.header }}</h2>
                </header>
                <form @submit="submitHanlder">
                    <slot></slot>
                    <footer><slot name="footer"></slot></footer>
                </form>
            </div>
        </Transition>
    </Teleport>
</template>

<script setup lang="ts">
import { computed, CSSProperties } from "vue";

import { Backdrop } from "@/components/ui";
import { FormSubmitHandler } from "@/types";

// Props
const props = defineProps<{
    show: boolean;
    header: string;
    onSubmit?: FormSubmitHandler;
    style?: CSSProperties;
    onCancel: () => void;
}>();

// Computed
const submitHanlder = computed(() => {
    if (props.onSubmit) {
        return props.onSubmit;
    } else {
        return (e: Event) => e.preventDefault();
    }
});
</script>

<style lang="css">
@reference "../../main.css";

@layer components {
    .modal-container {
        @apply fixed z-50 top-[22vh] left-[10%];
        @apply w-[80%] rounded-lg shadow-lg bg-surface;
        @apply md:left-1/2 md:w-160 md:-translate-x-1/2;
        @apply lg:w-200;
    }

    .modal-container header {
        @apply w-full rounded-t-lg p-4 bg-secondary text-pen-inverse;
    }

    .modal-container header h2 {
        @apply m-2 text-xl font-semibold;
    }

    .modal-container form > div {
        @apply p-4 min-h-30;
    }

    .modal-container form > footer {
        @apply flex justify-end space-x-2 p-4;
    }

    .modal-transition-enter-active,
    .modal-transition-leave-active {
        @apply transform transition-all duration-300 ease-out;
    }

    .modal-transition-enter-from,
    .modal-transition-leave-to {
        @apply -translate-y-20 opacity-0;
    }

    .modal-transition-enter-to,
    .modal-transition-leave-from {
        @apply -translate-y-0 opacity-100;
    }
}
</style>

// frontend-react/src/components/ui/Modal.tsx
import { Transition } from "@headlessui/react";
import { Fragment, ReactNode, useRef } from "react";
import { createPortal } from "react-dom";

import { FormSubmitHandler } from "../../types";
import Backdrop from "./Backdrop";

interface ModalOverlayProps {
    children: ReactNode;
    header: string;
    footer: ReactNode;
    onSubmit?: FormSubmitHandler;
    className?: string;
    style?: React.CSSProperties;
    headerClass?: string;
    contentClass?: string;
    footerClass?: string;
    ref?: React.RefObject<HTMLDivElement | null>;
}

const ModalOverlay: React.FC<ModalOverlayProps> = ({
    children,
    header,
    footer,
    onSubmit,
    className,
    style,
    headerClass,
    contentClass,
    footerClass,
    ref,
}) => {
    const content = (
        <div
            ref={ref}
            className={`fixed top-[22vh] left-[10%] w-[80%] bg-white rounded-lg shadow-lg z-50 md:left-1/2 md:w-[40rem] md:-translate-x-1/2 ${className}`}
            style={style}
        >
            <header
                className={`w-full p-4 bg-indigo-900 text-white ${headerClass}`}
            >
                <h2 className="m-2 text-xl font-semibold">{header}</h2>
            </header>
            <form onSubmit={onSubmit ? onSubmit : (e) => e.preventDefault()}>
                <div className={`p-4 ${contentClass}`}>{children}</div>
                <footer className={`p-4 ${footerClass}`}>{footer}</footer>
            </form>
        </div>
    );
    return createPortal(content, document.getElementById("modal-hook")!);
};

interface ModalProps extends ModalOverlayProps {
    show: boolean;
    onCancel: () => void;
}

const Modal: React.FC<ModalProps> = ({ show, onCancel, ...overlayProps }) => {
    const nodeRef = useRef<HTMLDivElement | null>(null);
    return (
        <>
            {show && <Backdrop onClick={onCancel} />}
            <Transition
                as={Fragment}
                show={show}
                enter="transition-all duration-300 ease-out transform"
                enterFrom="opacity-0 -translate-y-20"
                enterTo="opacity-100 translate-y-0"
                leave="transition-all transform"
                leaveFrom="opacity-100 translate-y-0"
                leaveTo="opacity-0 -translate-y-[100vh] duration-500 ease-in"
            >
                <ModalOverlay ref={nodeRef} {...overlayProps}></ModalOverlay>
            </Transition>
        </>
    );
};

export default Modal;
